microsoft/SynapseML

notebooks/samples/101 - Adult Census Income Training.ipynb
notebooks/samples/102 - Regression Example with Flight Delay Dataset.ipynb
notebooks/samples/103 - Before and After MMLSpark.ipynb
notebooks/samples/201 - Amazon Book Reviews - TextFeaturizer.ipynb
notebooks/samples/202 - Amazon Book Reviews - Word2Vec.ipynb
notebooks/samples/301 - CIFAR10 CNTK CNN Evaluation.ipynb
notebooks/samples/302 - Pipeline Image Transformations.ipynb

* Add a subsection `h2` heading to each notebook.
* Use a formatted print statement to display model metrics.
* Fix `CNKT` -> `CNTK` in [notebook 301](notebooks/samples/301%20-%20CIFAR10%20CNTK%20CNN%20Evaluation.ipynb)

Aesthetic improvements to sample notebooks

---

notebooks/samples/102 - Regression Example with Flight Delay Dataset.ipynb
notebooks/samples/201 - Amazon Book Reviews - TextFeaturizer.ipynb

Improved performance for flight delay dataset by marking columns as categoricals.
Fixed wording and removed not needed imports in amazon text featurization notebook.

Improvement to flight delay dataset notebook and other minor fixes

---

tools/hdi/install-mmlspark.sh
tools/hdi/update_livy.py

No need for `LD_STRING`, and remove some unnecessary boilerplate in
`update_livy.py`.

Minor script cleanup

---

notebooks/samples/303 - Transfer Learning by DNN Featurization - Airplane or Automobile.ipynb

Filling a gap in example Notebooks, to show DNN featurization together with SparkML model.

New example notebook to show transfer learning and DNN featurization

---

tools/runme/utils.sh

Instead of `.dev` followed by number of commits from the recent version
tag, use the number of commits from it that are on master, then `+`
followed by the number of commits since the branching point and the
usual `.g<sha1>`, finnaly followed by an optional `.local` and `.dirty`.
This makes it easier to identify older build materials that happen to
have lots of commits from new ones that have few commits.  The main
difference is in the `+` part so it shouldn't have any bad effects.
Also, be a little more strict in verifying tag versions: forbid a third
`0` component.

Improve version strings a bit

---

src/codegen/src/main/scala/PySparkWrapper.scala
src/core/schema/src/main/python/TypeConversionUtils.py
src/utils/src/main/python/java_params_patch.py

- Made the pipeline stage param a new param type
- Fix a problem with the complexTypeConverter
- fix the spark hardcoded namespace problem

Fix pipeline round-trip serialization

---

notebooks/samples/102 - Regression Example with Flight Delay Dataset.ipynb

Add ComputeModelStatistics to show RSME, and simplify import of TrainRegressor. Fixes issue #24

Fix issue #24: Improvement to 102 Regression example notebook

---

tools/build-pr/report
tools/config.sh
tools/misc/container-gc
tools/runme/build.sh

Much more robust, caches information, adds label feature, move to a
`deleted` container before deletions.
Also, rename `MAIN_CONTAINER` -> `MAIN_STORAGE`, which is what it
actually is.

Better `container-gc` script

---

tools/misc/container-gc
tools/runme/build.sh

There were supposed to go with the last commit, but I somehow lost them.

Two additional fixes

---

docs/azure-setup.md

Add instructions for ssh login to gpu vm and
vm shutdown. Changes created by @tongwen11.

update deployment links, add gpu vm instructions

---

tools/hdi/install-mmlspark.sh

* Use `conda info --envs` to get the environment names instead of
hard-wiring the list.
* Use an associative array to map env names to CNTK wheels.
* Move the `pip freeze` to after the environment activation, fixes a bug
where it would think that it's never installed.

Additional fixes for the cluster installation script

---

tools/misc/container-gc
tools/misc/mmlspark.svg

* Improvements to `container-gc`
* A quick svg version of the logo; it's a little different than the one
I made previously, so I'm not completely sure about it...

Misc things

---

README.md
docs/datasets.md
docs/developer-readme.md
docs/docker.md

Also, a few minor tweaks in other docs.

New docker documentation page

---

tools/deployment/bashshelldeploy.sh
tools/deployment/powershelldeploy.ps1

- Fix couple errors introduced during the last round of beautification
- Add a check on null resource group location when creating a new resource group
- Changes to make the coding style consistent

Update deployment scripts

---

notebooks/samples/101 - Adult Census Income Training.ipynb
notebooks/samples/102 - Regression Example with Flight Delay Dataset.ipynb
notebooks/samples/201 - Amazon Book Reviews - TextFeaturizer.ipynb
src/codegen/src/main/scala/PySparkWrapper.scala

Added fix to loading a model in wrapper generator, added verification (save/load model) in pyspark notebook

Added fix to loading a model in wrapper generator

---

src/core/env/src/main/scala/NativeLoader.java
src/core/schema/src/main/scala/ImageSchema.scala
src/project/build.scala

Using opencv from openpnp

---

tools/hdi/setup-ssh-keys.sh

Rename setup-ssh-keys to setup-ssh-keys.sh

Rename file: setup-ssh-keys -> setup-ssh-keys.sh

---

src/project/build.scala

Updating cntk to use maven repo

Updating cntk to use maven repo

---

src/codegen/src/main/scala/PySparkWrapperTest.scala
src/core/serialize/src/main/scala/params/PipelineStageParam.scala
src/ensemble/build.sbt
src/ensemble/src/main/scala/EnsembleByKey.scala
src/ensemble/src/test/scala/EnsembleByKeySuite.scala
src/fuzzing/src/test/scala/Fuzzing.scala
src/pipeline-stages/src/main/scala/Cacher.scala
src/pipeline-stages/src/main/scala/Repartition.scala
src/pipeline-stages/src/main/scala/Timer.scala
src/pipeline-stages/src/test/scala/CacherSuite.scala
src/pipeline-stages/src/test/scala/TimerSuite.scala

Note this depends on the ConstuctorSerializable commit
Adding:
Meta Estimator
Timer
Ensemble By Key
Cacher

Add new pipeline-stages

---

src/cntk-train/src/main/scala/CNTKLearner.scala
src/cntk-train/src/main/scala/CommandBuilders.scala

Adding username parameter for GPU VM to CNTKLearner

Adding username parameter for GPU VM to CNTKLearner

---

src/cntk-train/src/main/scala/CommandBuilders.scala

Adding better exception message if ssh connection not setup

Adding better exception message if ssh connection not setup

---

notebooks/gpu/401 - CNTK train on HDFS.ipynb

adding GPU training on HDFS notebook

adding GPU training on HDFS notebook

---

src/fuzzing/src/test/scala/Fuzzing.scala

Unbreak Fuzzing.scala

---

src/project/build.scala
tools/config.sh
tools/runme/install.sh
tools/runme/utils.sh

Also adds `azure-storage` as a dependency.

Add `hadoop-azure` to make wasb access work

---

src/project/build.scala
tools/config.sh
tools/misc/mmlspark.svg

Also ensure that the version number in SBT is the same as the downloaded
one.
Also simplify the SVG.

Download CNTK version 2.1

---

src/codegen/src/main/scala/PySparkWrapperTest.scala
src/image-featurizer/build.sbt
src/image-featurizer/src/main/scala/ImageSetAugmenter.scala
src/image-featurizer/src/test/scala/ImageSetAugmenterSuite.scala
src/image-transformer/src/main/python/ImageTransformer.py
src/image-transformer/src/main/scala/ImageTransformer.scala

Add a transformer that augments images with flips

Add the ImageAugmenter

---

src/codegen/src/main/scala/WrapperClassDoc.scala
src/partition-sample/src/main/scala/PartitionSample.txt
src/project/build.sbt
src/project/build.scala
src/project/lib-check.scala
src/project/meta.sbt
src/project/plugins.sbt
src/project/scalastyle.scala
tools/config.sh

* Java (zulu): zulu8.21.0.1 -> zulu8.23.0.3
* SBT: 0.13.15 -> 1.0.0

Update some installers

---

docs/azure-setup.md
tools/deployment/sparkClusterInVnetTemplate.json

- In the master ARM template, update the version of install-mmlspark.sh to 0.6
- In the setup document, correct/update with the new name for the script to setup password-less ssh connection
- In the setup document, update the example to open an ARM template in the portal with the GitHub url

Update deployment template and setup document with the updated links

---

src/cntk-model/src/main/scala/CNTKFunctionParam.scala
src/cntk-model/src/main/scala/CNTKModel.scala
src/cntk-model/src/main/scala/SerializableFunction.scala
src/cntk-model/src/test/scala/CNTKBindingSuite.scala
src/cntk-model/src/test/scala/CNTKModelSuite.scala
src/cntk-model/src/test/scala/CNTKTestUtils.scala
src/image-featurizer/src/main/scala/ImageFeaturizer.scala
src/project/scalastyle.scala

- Cache broadcasted model
- Default to byte array load

Optimize CNTK Model

---

README.md
notebooks/samples/304 - Medical Entity Extraction.ipynb
src/cntk-model/src/main/scala/CNTKModel.scala
tools/mmlspark-packages.spec

- also fix the CNTKmodel setOutputINodendex

Add Medical Entity extraction Notebook

---

src/cntk-model/src/main/scala/CNTKModel.scala
src/cntk-model/src/test/scala/CNTKBindingSuite.scala
src/cntk-model/src/test/scala/CNTKModelSuite.scala
src/cntk-model/src/test/scala/CNTKTestUtils.scala
src/core/serialize/src/test/scala/ValidateComplexParamSerializer.scala
src/core/test/base/src/main/scala/TestBase.scala
src/image-featurizer/src/main/python/ImageFeaturizer.py
src/image-featurizer/src/main/scala/ImageFeaturizer.scala

- Also refactor CNTKModel object for readability

Remove Inefficient Minibatch Padding

---

tools/docker/Dockerfile
tools/docker/Dockerfile-plus
tools/docker/bin/print-envvars
tools/docker/build-docker
tools/runme/build.sh

* `mmlspark`          -> `microsoft/mmlspark:X.Y`,          `microsoft/mmlspark:latest`
* `mmlspark-plus`     -> `microsoft/mmlspark:plus-X.Y`,     `microsoft/mmlspark:plus`
* `mmlspark-gpu`      -> `microsoft/mmlspark:gpu-X.Y`,      `microsoft/mmlspark:gpu`
* `mmlspark-plus-gpu` -> `microsoft/mmlspark:plus-gpu-X.Y`, `microsoft/mmlspark:plus-gpu`

Create more images

---

src/cntk-model/src/main/scala/SerializableFunction.scala
src/cntk-model/src/test/scala/CNTKModelSuite.scala
src/core/env/src/main/scala/NativeLoader.java
src/core/schema/src/main/scala/ImageSchema.scala
src/core/test/base/src/main/scala/TestBase.scala
src/image-transformer/src/main/scala/ImageTransformer.scala
src/readers/src/main/scala/ImageReader.scala

- The code previously loaded the natives for each partition which took a lot of memory, it now loads it once per machine
- This makes the build approx 15 min faster :)

Optimize OpenCV native loading

---

notebooks/samples/101 - Adult Census Income Training.ipynb
notebooks/samples/102 - Regression Example with Flight Delay Dataset.ipynb
notebooks/samples/103 - Before and After MMLSpark.ipynb
notebooks/samples/201 - Amazon Book Reviews - TextFeaturizer.ipynb
notebooks/samples/202 - Amazon Book Reviews - Word2Vec.ipynb
notebooks/samples/301 - CIFAR10 CNTK CNN Evaluation.ipynb
notebooks/samples/302 - Pipeline Image Transformations.ipynb
notebooks/samples/303 - Transfer Learning by DNN Featurization - Airplane or Automobile.ipynb
notebooks/samples/304 - Medical Entity Extraction.ipynb
notebooks/tests/BasicDFOpsSmokeTest.ipynb
src/clean-missing-data/src/main/scala/CleanMissingData.scala
src/clean-missing-data/src/test/scala/VerifyCleanMissingData.scala
src/core/env/src/main/scala/NativeLoader.java
src/core/schema/src/main/scala/BinaryFileSchema.scala
src/core/schema/src/main/scala/Categoricals.scala
src/core/utils/src/main/scala/CastUtilities.scala
src/find-best-model/src/main/scala/FindBestModel.scala
src/partition-sample/src/main/scala/PartitionSample.scala
src/train-regressor/src/main/scala/TrainRegressor.scala
src/value-indexer/src/main/scala/IndexToValue.scala
src/value-indexer/src/main/scala/ValueIndexer.scala
src/value-indexer/src/test/scala/VerifyValueIndexer.scala
tools/misc/check-notebooks.js
tools/misc/container-gc

Some additional style improvements.

Notebook style scan and verification scripts

---

tools/runme/info.tmpl

This made all `Build.md` files show as being a new version build.

Fix a typo when inspecting `$MML_LATEST`

---

src/fuzzing/src/test/scala/Fuzzing.scala
src/pipeline-stages/src/main/scala/ClassBalancer.scala
src/pipeline-stages/src/test/scala/ClassBalancerSuite.scala

- This pipeline stages calculates weights for estimators like LogisticRegression, so that one can correct for unbalanced datasets

Add a pipelineStage for calculating class balancing weights

---

src/cntk-train/src/main/scala/BrainscriptBuilder.scala
src/cntk-train/src/main/scala/CNTKLearner.scala
src/cntk-train/src/main/scala/CommandBuilders.scala
src/cntk-train/src/main/scala/DataConversion.scala
src/cntk-train/src/test/scala/ValidateDataConversion.scala
src/core/schema/src/main/scala/ImageSchema.scala

Adding GPU training with Parquet reader

gpu training with parquet reader

---

src/ensemble/src/main/scala/EnsembleByKey.scala
src/ensemble/src/main/scala/EnsembleByKey.txt

-workaround for default param issue

Fix pyspark default map param in EBK

---

tools/hdi/install-mmlspark.sh

Forgot to add the `$wheel` assignment; the problem was not reached since
the test cluster already has CNTK installed.

Fix an issue introduced in f1704d3

---

tools/hdi/install-mmlspark.sh
tools/misc/container-gc

* Make `container-gc` ignore the time of the label file.
* Missed the fact that the previous fix was not in a function, so
`local` is bogus.

Two small fixes

---

src/codegen/src/main/scala/PySparkWrapperTest.scala
src/pipeline-stages/src/main/scala/RenameColumn.scala
src/pipeline-stages/src/test/scala/RenameColumnSuite.scala

Add a transformer for withColumnRenamed

Add RenameColumn Transformer

---

src/codegen/src/main/scala/PySparkWrapperTest.scala
src/pipeline-stages/src/main/scala/TextPreprocessor.scala
src/pipeline-stages/src/test/scala/TextPreprocessorSuite.scala

Adding a Transformer that performs a replace all from left to right, preferring longer matches over all key value pairs in a dictionary. It does not replace replacement texts

Add TextPreprocessor Transformer

---

tools/misc/container-gc

Flag versions with missing content based on the version in which this
contents has been added.

Improve container-gc

---

README.md

Describe how to get MMLSpark via pip, and (indirectly) on aztk.

More README information, and a TOC

---

src/lightgbm/build.sbt
src/lightgbm/src/main/scala/LightGBM.scala
src/lightgbm/src/test/scala/VerifyLightGBM.scala
src/project/build.scala

Updating jar location, adding native load and network initialization

Updating jar location, adding native load and network initialization

---

src/lightgbm/src/main/scala/LightGBM.scala
src/lightgbm/src/test/scala/VerifyLightGBM.scala
src/project/build.scala

Adding code to create dataset and merge booster learners

Adding code to create dataset and merge booster learners

---

README.md
docs/gpu-setup.md
notebooks/gpu/401 - CNTK train on HDFS.ipynb

Extend/update documentation and notebook example for the multiple GPU VM support

Update documentation and notebook example 

---

src/lightgbm/src/main/scala/LightGBM.scala
src/lightgbm/src/test/scala/VerifyLightGBM.scala
src/project/build.scala

Adding logic to train a LightGBM model from spark

Adding logic to train a LightGBM model from spark

---

tools/build-pr/shared.sh

One issue is that `shared.sh` is loaded via the `@` function, and
therefore `declare` is local to the function.  Use `-g` instead.
Another issue is that `api` needs to keep cache state, and therefore it
should not be used in a `$(...)`.

Fix build-pr problems

---

src/lightgbm/src/main/scala/LightGBM.scala
src/lightgbm/src/test/scala/VerifyLightGBM.scala

Implement scoring logic for LightGBM and validate with tests

Implement inference logic for LightGBM

---

tools/build-pr/shared.sh

(Remove the regexp which I didn't actually use.)

Fix checking BUILDPR

---

src/codegen/src/main/scala/PySparkWrapperTest.scala
src/project/build.scala

Updating wrappers version, fixing python generated tests

Updating wrappers version, fixing python generated tests

---

notebooks/samples/203 - Breast Cancer - Tune Hyperparameters.ipynb
src/tune-hyperparameters/src/main/python/HyperparamBuilder.py
src/tune-hyperparameters/src/main/scala/DefaultHyperparams.scala
src/tune-hyperparameters/src/main/scala/HyperparamBuilder.scala

Adding python wrappers and notebook example for TuneHyperparameters

Adding python wrappers and notebook example for TuneHyperparameters

---

src/train-classifier/src/main/scala/TrainClassifier.scala
src/train-classifier/src/main/scala/TrainClassifier.txt

Fixed TrainClassifier documentation in python and R.
Thanks to Hang for finding this issue in R docs.

Fixed TrainClassifier documentation in python and R

---

src/lightgbm/src/main/scala/BlockManagerUtils.scala
src/lightgbm/src/main/scala/CSRUtils.scala
src/lightgbm/src/main/scala/LightGBMBooster.scala
src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMClassifier.txt
src/lightgbm/src/main/scala/LightGBMUtils.scala
src/lightgbm/src/main/scala/TrainUtils.scala
src/project/scalastyle.scala

Performing coalescing step inside train, optimizing code to retrieve nodes.
Adding code to handle sparse vectors in CSR format.

Performance updates and updates based on comments.

---

notebooks/samples/106 - Quantile Regression with LightGBM.ipynb
src/lightgbm/src/main/scala/LightGBMBooster.scala
src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/LightGBMUtils.scala
src/lightgbm/src/main/scala/TrainParams.scala

Adding alpha param and notebook example for lightGBM with quantile regression

Adding alpha param and notebook example for lightGBM with quantile regression

---

src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMParams.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/TrainParams.scala

These parameters were added:
maxBin, baggingFraction, baggingFreq, baggingSeed, featureFraction, maxDepth, minSumHessianInLeaf

Adding parameters to lightGBM classifier and regressor.

---

notebooks/gpu/401 - CNTK train on HDFS.ipynb
notebooks/samples/101 - Adult Census Income Training.ipynb
notebooks/samples/102 - Regression Example with Flight Delay Dataset.ipynb
notebooks/samples/103 - Before and After MMLSpark.ipynb
notebooks/samples/104 - Price Prediction Regression Auto Imports.ipynb
notebooks/samples/105 - Regression with DataConversion.ipynb
notebooks/samples/106 - Quantile Regression with LightGBM.ipynb
notebooks/samples/201 - Amazon Book Reviews - TextFeaturizer.ipynb
notebooks/samples/202 - Amazon Book Reviews - Word2Vec.ipynb
notebooks/samples/301 - CIFAR10 CNTK CNN Evaluation.ipynb
notebooks/samples/302 - Pipeline Image Transformations.ipynb
notebooks/samples/303 - Transfer Learning by DNN Featurization - Airplane or Automobile.ipynb
notebooks/samples/304 - Medical Entity Extraction.ipynb
notebooks/samples/305 - Flowers ImageFeaturizer.ipynb
notebooks/tests/BasicDFOpsSmokeTest.ipynb
tools/misc/check-notebooks.js
tools/notebook/postprocess.py

* version: 3.5.2 -> 3.6.3
* nbformat: 4.0 -> 4.2

Update notebook metadatas

---

src/lightgbm/src/main/scala/LightGBMParams.scala
src/lightgbm/src/main/scala/LightGBMUtils.scala

Hostname to IP Address conversion

Hostname to IP Address conversion

---

src/lightgbm/src/main/scala/LightGBMClassifier.scala

Ignore the second unused booster

---

src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/LightGBMUtils.scala
src/lightgbm/src/main/scala/TrainParams.scala

Although we already pass list of nodes to LightGBM, it still needs the numMachines param.

Passing numMachines param to LightGBM

---

notebooks/samples/301 - CIFAR10 CNTK CNN Evaluation.ipynb
notebooks/samples/303 - Transfer Learning by DNN Featurization - Airplane or Automobile.ipynb
notebooks/samples/304 - Medical Entity Extraction.ipynb
notebooks/samples/305 - Flowers ImageFeaturizer.ipynb
src/cntk-model/src/main/python/CNTKModel.py
src/cntk-model/src/main/scala/CNTKFunctionParam.scala
src/cntk-model/src/main/scala/CNTKModel.scala
src/cntk-model/src/main/scala/SerializableFunction.scala
src/cntk-model/src/test/scala/CNTKBindingSuite.scala
src/cntk-model/src/test/scala/CNTKModelSuite.scala
src/cntk-model/src/test/scala/CNTKTestUtils.scala
src/cntk-train/src/main/scala/CNTKLearner.scala
src/codegen/src/main/scala/PySparkWrapper.scala
src/core/serialize/src/main/scala/params/MapParam.scala
src/core/test/fuzzing/src/it/scala/NotebookTests.scala
src/image-featurizer/src/main/python/ImageFeaturizer.py
src/image-featurizer/src/main/scala/ImageFeaturizer.scala
src/image-featurizer/src/test/scala/ImageFeaturizerSuite.scala
src/project/scalastyle.scala

- Support Multi-In Multi-Out models
- Support feeding and fetching arbitrary graph nodes
- Support Graph nodes of mixed and varied datatypes
- Support Conversion to and From Vectors
- Support Turning Minibatching on and off

Generalize CNTK Model

---

src/codegen/src/main/scala/PySparkWrapperTest.scala
src/core/schema/src/main/scala/SparkBindings.scala
src/core/schema/src/test/scala/SparkBindingsTest.scala
src/core/spark/src/main/scala/FluentAPI.scala
src/core/test/base/src/main/scala/TestBase.scala
src/core/utils/src/main/scala/AsyncUtils.scala
src/io/binary/src/main/scala/BinaryFileFormat.scala
src/io/binary/src/main/scala/BinaryFileReader.scala
src/io/binary/src/test/scala/BinaryFileReaderSuite.scala
src/io/http/src/main/scala/Clients.scala
src/io/http/src/main/scala/HTTPClients.scala
src/io/http/src/main/scala/HTTPSchema.scala
src/io/http/src/main/scala/HTTPTransformer.scala
src/io/http/src/main/scala/Parsers.scala
src/io/http/src/main/scala/SimpleHTTPTransformer.scala
src/io/http/src/test/scala/SimpleHTTPTransformerSuite.scala
src/io/image/src/main/scala/Image.scala
src/io/image/src/main/scala/ImageFileFormat.scala
src/io/powerbi/src/main/scala/PowerBIWriter.scala
src/pipeline-stages/src/main/scala/Explode.scala
src/pipeline-stages/src/main/scala/Lambda.scala
src/pipeline-stages/src/main/scala/UDFTransformer.scala
src/pipeline-stages/src/test/scala/ExplodeSuite.scala
src/pipeline-stages/src/test/scala/LambdaSuite.scala

Several fixes

---

notebooks/samples/108 - Model Deployment with Spark Serving.ipynb

1. Changed port from 8888 to 8898 to not conflict with Jupyter port.
2. Removed label column from test example
3. Added a second test example that produces a response of 1.0
4. Leaving output cells in notebook, so folks can see what the notebook is supposed to produce.

changed port and added example

---

src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/TrainParams.scala
src/lightgbm/src/test/scala/VerifyLightGBMRegressor.scala

added tweedie variance power parameter to LightGBM regressor.
Note tweedie_variance_power >= 1.0 and < 2.0
Also added test which uses cross validator.
resolves issue #353

added tweedie variance power to LightGBM

---

src/codegen/src/main/scala/WrapperGenerator.scala
src/downloader/src/main/R/model_downloader.R

added model downloader R wrapper

added model downloader R wrapper

---

src/lightgbm/src/main/scala/LightGBMBooster.scala
src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMParams.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/LightGBMUtils.scala
src/lightgbm/src/main/scala/TrainParams.scala
src/lightgbm/src/main/scala/TrainUtils.scala
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala

Support LightGBM continue training from a previously trained model.

Support LightGBM continue training

---

src/lightgbm/src/main/scala/TrainUtils.scala
src/lightgbm/src/test/resources/benchmarks_VerifyLightGBMClassifier.csv
src/lightgbm/src/test/resources/benchmarks_VerifyLightGBMRegressor.csv
src/lightgbm/src/test/scala/VerifyLightGBMRegressor.scala
src/project/build.scala

resolves frozen notebook issue: https://github.com/Azure/mmlspark/issues/341
related PR: https://github.com/Microsoft/LightGBM/pull/1593

lightgbm version update, resolves frozen notebook issue

---

notebooks/samples/106 - Quantile Regression with LightGBM.ipynb
src/codegen/src/main/scala/WrapperGenerator.scala
src/lightgbm/src/main/python/LightGBMClassifier.py
src/lightgbm/src/main/python/LightGBMRegressor.py
src/lightgbm/src/main/scala/LightGBMBooster.scala
src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala

adding load native LightGBM model from string and file API
Fixes issue https://github.com/Azure/mmlspark/issues/293

adding load native LightGBM model from string and file API

---

notebooks/samples/101 - Adult Census Income Training.ipynb
notebooks/samples/102 - Regression Example with Flight Delay Dataset.ipynb
notebooks/samples/105 - Regression with DataConversion.ipynb
src/core/serialize/src/main/scala/Serializer.scala

fixes issue https://github.com/Azure/mmlspark/issues/305

fix overwrite for metadata file

---

notebooks/samples/201 - Amazon Book Reviews - TextFeaturizer.ipynb
notebooks/samples/202 - Amazon Book Reviews - Word2Vec.ipynb
src/find-best-model/src/main/python/FindBestModel.py
src/find-best-model/src/main/scala/FindBestModel.scala

adding FindBestModel wrapper and updating notebook examples

adding FindBestModel wrapper and updating notebook examples

---

docs/R-setup.md
src/codegen/src/main/scala/SparklyRWrapper.scala

resolves issue https://github.com/Azure/mmlspark/issues/375

add untrained model and databricks example for R

---

src/io/http/src/test/scala/services/ImageSearchSuite.scala

@imatiach-msft this is the issue you were facing!

Fix flaky bing test

---

src/lightgbm/src/main/scala/LightGBMBooster.scala
src/lightgbm/src/main/scala/TrainUtils.scala

fixes issue https://github.com/Azure/mmlspark/issues/387

add serial version UID to Serializable LightGBMBooster

---

src/core/env/src/main/scala/EnvironmentUtils.scala

Use scala sys API in utils

---

notebooks/samples/LightGBM - Quantile Regression for Drug Discovery.ipynb
src/lightgbm/src/main/python/LightGBMClassifier.py
src/lightgbm/src/main/python/LightGBMRegressor.py

view the feature importances as a list instead of JavaArray
resolves issue https://github.com/Azure/mmlspark/issues/416

view the feature importances as a list instead of JavaArray

---

src/core/contracts/src/main/scala/Params.scala
src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMParams.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/TrainUtils.scala
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
src/lightgbm/src/test/scala/VerifyLightGBMRegressor.scala

adding weight column to lightgbm + tests
resolves issue: https://github.com/Azure/mmlspark/issues/411

adding weight column to lightgbm

---

src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMParams.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/TrainParams.scala
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala

adding isunbalance param and verbosity param (plus test)
resolves issue: #408

adding isunbalance param and verbosity param

---

src/core/env/src/main/scala/NativeLoader.java
src/lightgbm/src/main/scala/LightGBMUtils.scala

fixes issue https://github.com/Azure/mmlspark/issues/443

added OS prefix for lightgbm on windows

---

src/project/build.scala

updated lightgbm to 2.2.2
resolves issue https://github.com/Azure/mmlspark/issues/390

updated lightgbm to 2.2.2

---

src/io/http/src/test/scala/services/ComputerVisionSuite.scala
src/lightgbm/src/main/scala/LightGBMBooster.scala
src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMConstants.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/TrainParams.scala
src/lightgbm/src/test/resources/benchmarks_VerifyLightGBMClassifier.csv
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala

adding support for multiclass classification in LightGBM
resolves issue #342

adding support for multiclass classification

---

src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMParams.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/TrainParams.scala

resolves https://github.com/Azure/mmlspark/issues/471

added boost from average parameter to LightGBM

---

docs/lightgbm.md

Fix broken notebook link, see issue #490

Fix link to example notebook

---

src/recommendation/src/main/scala/SARModel.scala
src/recommendation/src/test/scala/SARSpec.scala

Adding the following functions to SAR Model to align with ALS. 
RecommendForUserSubset

Add Recommend For User Subset to SAR

---

src/recommendation/src/main/scala/RecommendationIndexer.scala
src/recommendation/src/test/python/RankingSpec.py
src/recommendation/src/test/scala/RankingTestBase.scala
src/recommendation/src/test/scala/RankingTrainValidationSpec.scala
src/recommendation/src/test/scala/RecommendationIndexerSpec.scala
src/recommendation/src/test/scala/SARSpec.scala

Used for indexing inputs for recommendation models, both ALS and SAR.

Adding Recommendation Indexer

---

src/lightgbm/src/main/scala/TrainUtils.scala

This patch ensures translate() method correctly stops processing when encountering an empty partition.
This prevents a crash when using LightGBM in python with CrossValidation and n_folds > 1.

[LightGBM] Ensure TrainUtils.translate() doesn't crash on an empty partition

---

src/lightgbm/src/main/scala/LightGBMBase.scala
src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/TrainParams.scala
src/lightgbm/src/main/scala/TrainUtils.scala

refactoring common code between LightGBMClassifier and LightGBMRegressor to common base class in preparation for https://github.com/Azure/mmlspark/issues/446

refactor lightgbm common code to base class

---

src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMParams.scala
src/lightgbm/src/main/scala/LightGBMRegressor.scala
src/lightgbm/src/main/scala/TrainParams.scala
src/lightgbm/src/main/scala/TrainUtils.scala
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
src/lightgbm/src/test/scala/VerifyLightGBMRegressor.scala

added L1 regularization and L2 regularization parameters to lightgbm classifier and regressor
added retry logic for NetworkInit method to prevent failing on socket bind errors
Resolves issue https://github.com/Azure/mmlspark/issues/548

added L1 regularization and L2 regularization

---

src/lightgbm/src/main/scala/LightGBMDataset.scala
src/lightgbm/src/main/scala/LightGBMUtils.scala
src/lightgbm/src/main/scala/TrainUtils.scala
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
src/project/build.scala

resolves issue https://github.com/Azure/mmlspark/issues/332

pass through slot names to native structure

---

src/core/metrics/src/main/scala/MetricUtils.scala

fixes issue https://github.com/Azure/mmlspark/issues/557

improved compute model statistics error message

---

src/io/http/src/main/scala/schemas/AnomalyDetectorSchemas.scala
src/io/http/src/main/scala/schemas/SpeechSchemas.scala
src/io/http/src/main/scala/services/AnamolyDetection.scala
src/io/http/src/main/scala/services/AzureSearchAPI.scala
src/io/http/src/main/scala/services/CognitiveServiceBase.scala
src/io/http/src/main/scala/services/ComputerVision.scala
src/io/http/src/main/scala/services/FaceAPI.scala
src/io/http/src/main/scala/services/Speech.scala
src/io/http/src/test/scala/services/AnamolyDetectionSuite.scala
src/io/http/src/test/scala/services/SpeechSuite.scala
src/project/build.scala
tools/runme/build.sh

Add anomaly detection and speech to text services

---

src/core/contracts/src/main/scala/Params.scala
src/lightgbm/src/main/scala/LightGBMBase.scala
src/lightgbm/src/main/scala/LightGBMDataset.scala
src/lightgbm/src/main/scala/LightGBMParams.scala
src/lightgbm/src/main/scala/TrainUtils.scala
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala

resolves issue https://github.com/Azure/mmlspark/issues/382

add init score column for continued training + test

---

src/core/contracts/src/main/scala/Params.scala
src/core/test/benchmarks/src/main/scala/Benchmarks.scala
src/core/test/fuzzing/src/test/scala/FuzzingTest.scala
src/downloader/src/main/scala/ModelDownloader.scala
src/downloader/src/test/scala/DownloaderSuite.scala
src/io/http/src/test/scala/services/ComputerVisionSuite.scala
src/lightgbm/src/main/scala/LightGBMBase.scala
src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/main/scala/LightGBMConstants.scala
src/lightgbm/src/main/scala/LightGBMDataset.scala
src/lightgbm/src/main/scala/LightGBMRanker.scala
src/lightgbm/src/main/scala/LightGBMRanker.txt
src/lightgbm/src/main/scala/LightGBMRegressor.txt
src/lightgbm/src/main/scala/LightGBMUtils.scala
src/lightgbm/src/main/scala/Ranker.scala
src/lightgbm/src/main/scala/TrainParams.scala
src/lightgbm/src/main/scala/TrainUtils.scala
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
src/lightgbm/src/test/scala/VerifyLightGBMRanker.scala
tools/config.sh

resolves https://github.com/Azure/mmlspark/issues/543 and https://github.com/Azure/mmlspark/issues/446
TODO: Add tests once new lightgbm native jar uploaded

adding LightGBMRanker

---

src/lightgbm/src/main/scala/LightGBMBase.scala
src/lightgbm/src/main/scala/TrainUtils.scala
src/lightgbm/src/test/scala/VerifyLightGBMRanker.scala

fixes issue https://github.com/Azure/mmlspark/issues/573

fix query column to support long type

---

src/lightgbm/src/main/scala/LightGBMClassifier.scala
src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala

fixes issue https://github.com/Azure/mmlspark/issues/568

defer lightgbm probability calculation to native core to fix multiclass bug in some scenarios

---

src/io/powerbi/src/test/scala/PowerBiSuite.scala
src/summarize-data/src/main/scala/SummarizeData.scala
src/summarize-data/src/test/scala/SummarizeDataSuite.scala

fixes issue https://github.com/Azure/mmlspark/issues/585

fix summarize data column names

---

src/codegen/src/main/scala/WrapperGenerator.scala
src/lightgbm/src/main/python/LightGBMRanker.py

added lightgbm ranker model pyspark api
fix for issue https://github.com/Azure/mmlspark/issues/591

added lightgbm ranker model pyspark api

---

src/codegen/src/main/scala/PySparkWrapper.scala
src/codegen/src/main/scala/SparklyRWrapper.scala

resolves issue #595 for lightgbm ranker

fix default value for double array param in codegen

---

docs/vagrant.md
tools/vagrant/Vagrantfile

Adding doc on using Vagrant, missed pushing this into #622 before it merged
also fixing indentation in Vagrantfile

adding vagrant doc and fixing indentation in vagrantfile

---

src/main/scala/com/microsoft/ml/spark/core/utils/ClusterUtil.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
src/main/scala/com/microsoft/ml/spark/vw/VowpalWabbitBase.scala

adding some debug and using num executors-1 for client mode
investigating issue https://github.com/Azure/mmlspark/issues/588

fix: client mode for issue 588, adding more debug for future investigations

---

build.sbt
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala

update lightgbm to 2.3.100, remove generateMissingLabels, fix lightgbm getting stuck on unbalanced data

fix: update lightgbm to 2.3.100, remove generateMissingLabels, fix lightgbm getting stuck on unbalanced data

---

src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala

fixes issue https://github.com/Azure/mmlspark/issues/703
specifically, filters the training data if validation index column is present, and adds preprocessing to validation data for ranking

fix: validation data and ranker preprocessing

---

src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala

fixed early stopping test for validation dataset
added comments that the first model should overfit on the training dataset and the second should terminate early, thereby giving a better evaluation metric

fix: early stopping test for validation dataset

---

notebooks/samples/Regression - Vowpal Wabbit vs. LightGBM vs. Linear Regressor.ipynb
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRegressor.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala
src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala

fix: added max_bin_by_feature, min_gain_to_split, max_delta_step parameters
resolves https://github.com/Azure/mmlspark/issues/687

fix: added max_bin_by_feature, min_gain_to_split, max_delta_step parameters

---

src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRegressor.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala

Adding a feature for positive and negative bagging fraction params.
Keunhyun Oh <keunhyun.oh@ahnlab.com>

feat: Adding a feature for positive and negative bagging fraction params.

---

build.sbt

updated lightgbm to 2.3.150
needed for https://github.com/Azure/mmlspark/pull/730

fix: updated lightgbm to 2.3.150

---

src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRegressor.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala

fix: added min_data_in_leaf parameter
resolves issue https://github.com/Azure/mmlspark/issues/746

fix: added min_data_in_leaf parameter

---

src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMConstants.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala

resolves issue https://github.com/Azure/mmlspark/issues/719

fix: add cap on max allowed port in network init

---

src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBooster.scala

Changes needed for:
https://github.com/Azure/mmlspark/issues/720
NOTE: Requires https://github.com/microsoft/LightGBM/pull/2560 to be merged before this, since we will be calling the SWIG function.
EDIT: The PR on the LightGBM repo has been merged, so this should be safe to merge now.

feat: Expose dump model method on MMLSpark-LightGBM so that models can be saved as json.

---

src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBooster.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala

feat: add leaf index prediction for LightGBMClassifier
Keunhyun Oh <keunhyun.oh@ahnlab.com>

feat: add leaf index prediction for LightGBMClassifier

---

notebooks/samples/ConditionalKNN - Exploring Art Across Cultures.ipynb
src/it/scala/com/microsoft/ml/nbtest/DatabricksUtilities.scala
src/main/scala/com/microsoft/ml/spark/nn/BallTree.scala
src/main/scala/com/microsoft/ml/spark/nn/ConditionalKNN.scala
src/test/scala/com/microsoft/ml/spark/nn/BallTreeTest.scala
src/test/scala/com/microsoft/ml/spark/nn/ConditionalBallTreeTest.scala

Co-authored-by: Mindren Lu <mdlu841@gmail.com>
Co-authored-by: Stephanie Fu <fus@mit.edu>

feat: add demo for `ConditionalKNN`

---

README.md

updated README with section for Apache Livy install issues

fix: Adding section to readme for installing with apache livy

---

src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMConstants.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala

feat: add driver listen port option.
It is needed in network environment strictly managed by firewall.
contacts: keunhyun.oh@ahnlab.com
@AhnLab-OSS

feat: add driver listen port option 

---

build.sbt

build: Bump Apache Spark to 2.4.5

---

src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala

fix: re-disable flaky test

---

src/main/python/mmlspark/cyber/anomaly/collaborative_filtering.py
src/test/python/mmlsparktest/cyber/anamoly/test_collaborative_filtering.py

add + test a save/load method to AccessAnomalyModel

add save and load methods to AccessAnomalyModel

---

src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
src/test/scala/com/microsoft/ml/spark/lightgbm/split2/VerifyLightGBMRegressor.scala

fix: improve error message for invalid slot names
resolves
https://github.com/Azure/mmlspark/issues/887
related LightGBM code for special characters:
https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/utils/common.h#L965

fix: improve error message for invalid slot names

---

src/main/scala/com/microsoft/ml/spark/cognitive/SpeechSchemas.scala
src/main/scala/com/microsoft/ml/spark/cognitive/SpeechToTextSDK.scala

feat: add m4a codec

---

src/main/python/mmlspark/recommendation/RankingTrainValidationSplit.py
src/main/python/mmlspark/recommendation/RankingTrainValidationSplitModel.py
src/main/python/mmlspark/recommendation/SAR.py
src/main/python/mmlspark/recommendation/SARModel.py
src/main/python/mmlspark/recommendation/ValidatorSetterParams.py
src/test/python/mmlsparktest/recommendation/test_ranking.py

Fixing some bugs that popped up with Spark 3.

fix: Recommender Patch for Spark 3 Update

---

src/main/scala/com/microsoft/ml/spark/lime/BreezeUtils.scala
src/main/scala/com/microsoft/ml/spark/lime/LIME.scala
src/main/scala/com/microsoft/ml/spark/lime/TextLIME.scala
src/test/scala/com/microsoft/ml/spark/lime/LIMESuite.scala
src/test/scala/com/microsoft/ml/spark/lime/TextLIMESuite.scala

Co-authored-by: Sharath AbbarajuVenkata <Sharat.AbbarajuVenkata@microsoft.com>
Co-authored-by: Mark Hamilton <marhamil@microsoft.com>

feat: add TextLIME

---

CODEOWNERS

fix: Adding @miguelgfierro, @gramhagen, @eisber  as recommendation code owners.

fix: adding more recommendation code owners

---

pipeline.yaml
tools/docker/demo/Dockerfile
tools/docker/developer/Dockerfile
tools/docker/minimal/Dockerfile

Synapse BBC-VHD for Spark 3 is now updating to ubuntu 18.04

update ubuntu version to 18.04

---

src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala

- re-enable early stopping test
- add average precision metric to comparison logic for early stopping

fix: early stopping test and average precision metric

---

src/main/scala/com/microsoft/ml/spark/lime/LIME.scala

#[1049]
Thanks to @memoryz  for finding this!

fix: Fix issue in tabular lime sampler

---

src/main/scala/com/microsoft/ml/spark/cognitive/ImageSearchSchemas.scala

[AB#1208746](https://msdata.visualstudio.com/b9b2accc-2d1c-45b3-9d24-0eb5d78cc47f/_workitems/edit/1208746)

fix: small issue with null in bing image response

---

src/main/scala/com/microsoft/ml/spark/io/http/SharedVariable.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMConstants.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
src/main/scala/com/microsoft/ml/spark/lightgbm/booster/LightGBMBooster.scala
src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala

sending this PR in preparation for https://github.com/Azure/mmlspark/pull/1066 to reduce the amount of code in other PR.  This PR just contains some code refactoring, no changes to functionality.

feat: refactoring of lightgbm code in preparation for single dataset mode

---

src/main/scala/com/microsoft/ml/spark/cognitive/TextAnalyticsSDK.scala
src/test/scala/com/microsoft/ml/spark/cognitive/split1/TextAnalyticsSDKSuite.scala

Fixed PR and included suggestions from mentors and team

feat: Sentiment PR with SDK Integration - Refactored 

---

src/main/scala/com/microsoft/ml/spark/cognitive/TextAnalyticsSDK.scala
src/test/scala/com/microsoft/ml/spark/cognitive/split1/TextAnalyticsSDKSuite.scala

Implements asynch features with parameterized timeout and concurrency inputs.

feat: Asynch implementation on clean branch

---

README.md

The current link is not available. Thus, I updated the link.

Update notebook link on README

---

cognitive/src/main/scala/com/microsoft/ml/spark/cognitive/TextAnalyticsSDK.scala
cognitive/src/test/scala/com/microsoft/ml/spark/cognitive/split1/TextAnalyticsSDKSuite.scala

This PR adds a key rotation update for Text Analytics methods.

Text Analytics Key rotation

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalyticsSchemas.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala

Add `redactedText` API response to `PIIDocV3` schema type
Closes #1246

feat: Add redactedText to PIIDocV3

---

lightgbm/src/main/python/synapse/ml/lightgbm/mixin.py
lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMClassifier.scala
lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRanker.scala
lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRegressor.scala
lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/booster/LightGBMBooster.scala
lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/params/LightGBMParams.scala
lightgbm/src/test/scala/com/microsoft/azure/synapse/ml/lightgbm/split1/VerifyLightGBMClassifier.scala

feat: add predict_disable_shape_check in LightGBM

---

core/src/main/scala/com/microsoft/azure/synapse/ml/stages/MiniBatchTransformer.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/stages/MiniBatchTransformerSuite.scala

feat: Allow FlattenBatch to propagate non-array values

---

README.md

Update README: fix broken link to CyberML notebook

---

core/src/main/python/synapse/ml/isolationforest/IsolationForestModel.py
core/src/main/scala/com/microsoft/azure/synapse/ml/isolationforest/IsolationForest.scala
src/test/scala/com/microsoft/azure/synapse/ml/core/test/fuzzing/FuzzingTest.scala

fix: IsolationForestModel does not properly exchange params with the inner model

---

build.sbt
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/CognitiveServiceBase.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/MultivariateAnomalyDetection.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalytics.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalyticsSDK.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalyticsSDKSchemasV4.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSDKSuite.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/core/contracts/Params.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/HTTPTransformer.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/SimpleHTTPTransformer.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/stages/PartitionConsolidator.scala

Co-authored-by: Assaf Israel <assafi@microsoft.com>
Co-authored-by: Assaf Israel <assaf.israel@microsoft.com>
Co-authored-by: Samantha Konigsberg <t-samanthak@microsoft.com>
Co-authored-by: victoriajmicrosoft <victoriajmicrosoft@users.noreply.github.com>
Co-authored-by: Suhas Mehta <suhas.mehta@microsoft.com>
Co-authored-by: Preeti Pidatala <t-ppidatala@microsoft.com>

feat: TextAnalytics SDK connector POC

---

.github/workflows/ado-integration.yml

Updating AzDO Integration w/ correct states for Task (To Do, In Progress, Done) for the process template the Team is using.

fix: Updating AzDO Integration with correct states

---

.github/workflows/ado-pr-to-workitem.yml
website/docs/reference/developer-readme.md

Making fine tunes to try out the PR to WI integration.........

fix: ado-pr-workitem yaml

---

.github/pull_request_template.md

Adding a PR template to the repo to minimize PRs with empty body.

chore: Adding a PR template

---

website/docusaurus.config.js

fix: fix website gtag

---

README.md
core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/HTTPClients.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksTests.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/SynapseTests.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/SynapseUtilities.scala
pipeline.yaml
project/build.scala
templates/codecov.yml
templates/conda.yml
templates/kv.yml
templates/update_cli.yml

- Added better error messages for E2E test failures
- Added overwrites on azure blob upload

chore: fix build flakiness

---

website/BingSiteAuth.xml

chore: Adding Bing Analytics configuration 

---

cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split4/MultivariateAnamolyDetectionSuite.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksTests.scala
notebooks/features/geospatial_services/GeospatialServices - Flooding Risk.ipynb
notebooks/features/geospatial_services/GeospatialServices - Overview.ipynb

chore: fix flakes in geospatial notebooks

---

notebooks/features/responsible_ai/Interpretability - PDP and ICE explainer.ipynb

Added documentation about PDP-based feature importance option for kind == `feature`. Added API calls and visualizations.
N/A
N/A

docs: Updated ICE/PDP doc with PDP-based feature importance

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalyticsSchemas.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala

Fix hasOpinion mining output for text sentiment
see diff

feat: add opinion mining to text sentiment v3

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/MultivariateAnomalyDetection.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split4/MultivariateAnamolyDetectionSuite.scala

fix MVAD error message
Add test cases

fix: fix error message of MVAD

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/MultivariateAnomalyDetection.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split4/MultivariateAnamolyDetectionSuite.scala

Merge fix of MVAD
Added test cases.

fix: merge fix of MVAD

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/MultivariateAnomalyDetection.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split4/MultivariateAnamolyDetectionSuite.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/HTTPClients.scala

Add automatic cleanup ability for MVAD tests

build: clean up extra mvad models and improve network resilliancy

---

.github/workflows/ado-integration.yml
.github/workflows/ado-pr-to-workitem.yml

Fix auto pm

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalytics.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalyticsAnalyzeSchemas.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalyticsSchemas.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalyticsSchemasV2.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/codegen/DefaultParamInfo.scala
environment.yaml
pipeline.yaml
templates/conda.yml

fix: fix error in TA Analyze schema

---

pipeline.yaml

chore: increase component governance timeout

---

.github/pull_request_template.md
core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksTests.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala
pipeline.yaml

Should check library installation status before submitting jobs for databricksTest
Ran Databricks test
None.
AB#1759003

fix: fix library checking while installing library on databricks cluster

---

pipeline.yaml

chore: add component governence explicitly to build so timeout variable works

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/CognitiveServiceBase.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/OpenAI.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/OpenAISchemas.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/ParamBoilerplateGen.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/OpenAISuite.scala
core/src/main/scala/org/apache/spark/ml/param/JsonEncodableParam.scala
core/src/main/scala/org/apache/spark/ml/param/UntypedArrayParam.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/Secrets.scala

Add the OpenAI Text Completion cognitive service
See `OpenAISuite.scala`
None
AB#1766734

feat: add OpenAICompletion model

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/OpenAI.scala

fix: Fix setServiceName python method in OpenAI

---

tools/docker/demo/Dockerfile
tools/docker/minimal/Dockerfile
tools/helm/livy/Dockerfile
tools/helm/spark/Dockerfile
tools/helm/spark/mini.Dockerfile
tools/helm/zeppelin/Dockerfile

chore: update docker images to remain compliant

---

.github/workflows/semantic_pr.yaml

chore: fix semantic PR checking

---

core/src/test/scala/com/microsoft/azure/synapse/ml/core/test/base/TestBase.scala

Fixes spelling typo in a file.
N/A
N/A
AB#1779545

fix: typo in TestBase

---

hooks/pre-commit

chore: streamline scalastyle hook

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/FormRecognizerV3.scala

support CustomModel of Form Recognizer v3
Will add test cases
None.
AB#1860290

feat: support CustomModel of Form Recognizer v3

---

lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/params/LightGBMParams.scala

Improve parameter doc based on issue https://github.com/microsoft/SynapseML/issues/1552
N/A
N/A
AB#1866908

fix: Fix doc for numThreads

---

lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/params/LightGBMParams.scala

Doc is outdated for useSingleDatasetMode, as noted in https://github.com/microsoft/SynapseML/issues/1558. Updated.
AB#1868724

fix: Fix outdated doc for useSingleDatasetMode

---

build.sbt
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/FaceSuite.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/core/utils/JarLoadingUtils.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split1/TabularLIMEExplainerSuite.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split1/TabularSHAPExplainerSuite.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split1/TextExplainersSuite.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split1/VectorLIMEExplainerSuite.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split1/VectorSHAPExplainerSuite.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/recommendation/RankingTestBase.scala
deep-learning/src/test/scala/com/microsoft/azure/synapse/ml/explainers/ImageExplainersSuite.scala
deep-learning/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split2/ImageLIMEExplainerSuite.scala
deep-learning/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split3/ImageSHAPExplainerSuite.scala
project/plugins.sbt
tools/docker/demo/Dockerfile
tools/docker/minimal/Dockerfile

azure-storage-blob 12.14.2->12.14.4
AB#1877299

chore: update azure storage blob version

---

.github/workflows/acknowledge-new-issues.yml
.github/workflows/acknowledge-new-prs.yml
.github/workflows/label-add-triage.yml

These new workflows will help provide a better experience to our OSS community, users by providing them an acknowledgement message right after they post a new PR / Issue.
Source: https://github.com/marketplace/actions/create-or-update-comment
Will test this workflow after it gets merged to master.
None.
AB#1889601

chore: Add welcome message to new PRs/Issues

---

core/src/test/scala/com/microsoft/azure/synapse/ml/exploratory/FeatureBalanceMeasureSuite.scala
deep-learning/src/test/scala/com/microsoft/azure/synapse/ml/cntk/ImageFeaturizerSuite.scala
deep-learning/src/test/scala/com/microsoft/azure/synapse/ml/explainers/ImageExplainersSuite.scala
deep-learning/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split3/ImageSHAPExplainerSuite.scala

Signed-off-by: Jason Wang <jasowang@microsoft.com>
Trying to stabilize 2 flaky unit tests. 
AB#1890042

test: stabilize unit tests

---

.github/pull_request_template.md
website/src/pages/videos.js

Add demo video on website
Rendered website
None.
AB#1892522

docs: add demo into videos on website

---

notebooks/features/cognitive_services/CognitiveServices - OpenAI.ipynb

Improving the copy on the openAi notebook
AB#1912948

docs: improve OpenAI notebook

---

.github/dependabot.yml

#xxx
Add a dependabot file to update the versions of the Github Actions used for CI jobs
This requires to create a dependabot.yml file and to enable dependabot in the settings of the repository
I applied it in my fork and it proposed the correct updates (and a security alert).
https://github.com/iemejia/SynapseML/pulls
4. Navigate to website folder, and run …

Automatic version updates for github actions with dependabot

---

pipeline.yaml

None
Try to fix python tests as it's taking such a long time
AB#1948990

fix: python tests

---

notebooks/community/aisamples/AIsample - Book Recommendation.ipynb
notebooks/community/aisamples/AIsample - Fraud Detection.ipynb
notebooks/community/aisamples/AIsample - Title Genre Classification.ipynb

None
Updated aisample notebooks. 
- Added sections for mlflow logging and loading. 
- Updated pip install with magic command.
AB#1958014

docs: add mlflow logging and loading

---

notebooks/community/aisamples/AIsample - Uplift Modelling.ipynb

None
Add a uplift modelling notebook for aisample under notebooks/community/aisample.
AB#1957564

docs: add aisample uplift modelling

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/SynapseTests.scala
notebooks/features/classification/Classification - Sentiment Analysis Quickstart.ipynb

chore: turn off failing synapse tests temporarily

---

notebooks/community/aisamples/AIsample - Time Series Forecasting.ipynb

None
- Remind users to restart notebook session after adding new lakehouse.
- Fix multiple typos.

docs: fix multiple typos and update error msg in ai-sample notebook

---

website/docs/reference/developer-readme.md
website/versioned_docs/version-0.10.1/reference/developer-readme.md

docs: update developer readme instruction on python env creation

---

.github/workflows/ado-integration.yml
.github/workflows/ado-pr-to-workitem.yml

chore: fix ado integration

---

templates/update_cli.yml

chore: pin az and python versions

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/SynapseTests.scala
notebooks/features/vw/Vowpal Wabbit - Overview.ipynb

#xxx
Changes in notebook are made at line 532. change pandas df to spark df for display.

fix: remove Vowpal Wabbit exclusion, add Interpretability exclusion

---

.github/workflows/scripts/clean-acr.py

chore: fix style

---

website/package.json
website/yarn.lock

chore: bump docusaurus

---

.github/ISSUE_TEMPLATE/bug_report_template.yaml
build.sbt
core/src/main/scala/com/microsoft/azure/synapse/ml/logging/BasicLogging.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/codegen/RTestGen.scala
environment.yml
lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRanker.scala
lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRegressor.scala
lightgbm/src/test/scala/com/microsoft/azure/synapse/ml/lightgbm/split2/VerifyLightGBMRegressor.scala
start
tools/docker/demo/Dockerfile
tools/docker/minimal/Dockerfile
tools/tests/run_r_tests.R
vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitContextualBandit.scala
vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitRegressor.scala

chore: fix build by bumping spark to 3.2.3

---

environment.yml
templates/conda.yml

chore: fix conda env creation

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/anomaly/MultivariateAnomalyDetection.scala

fix: delete too many anomaly models

---

core/src/main/scala/com/microsoft/azure/synapse/ml/causal/DoubleMLEstimator.scala

I did not find any related PRs
#xxx
In the isolation forest [example notebook](https://github.com/microsoft/SynapseML/blob/master/notebooks/features/isolation_forest/IsolationForest%20-%20Multivariate%20Anomaly%20Detection.ipynb), `udf` is used to convert a vector to array 
`vec2array = udf(lambda vec: vec.toArray().tolist(), ArrayType(FloatType()))` . However, `udf` is not imported into resulting into an error when the notebook is run.  This can be resolved with below change: 
`vec2array = F.udf(lambda vec: vec.toArray().tolist(), ArrayType(FloatType()))`
By running the notebook.
2. Follow the pattern in …

fix: fix annamespace import for Experimental (#1780)

---

website/README.md
website/docs/features/responsible_ai/Data Balance Analysis.md
website/docs/features/simple_deep_learning/about.md
website/docs/features/spark_serving/about.md
website/docs/features/vw/about.md

#xxx
Linx fixes for README and features

chore: linx fixes for README and features

---

pipeline.yaml

test: fix issue with missing causal tests

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/SynapseTests.scala

chore: disable Interpretability tests

---

pipeline.yaml

chore: Disable synapse-extension tests, add params to pipeline

---

website/docs/about.md
website/versioned_docs/version-0.10.0/about.md
website/versioned_docs/version-0.10.1/about.md
website/versioned_docs/version-0.10.2/about.md
website/versioned_docs/version-0.9.4/about.md
website/versioned_docs/version-0.9.5/about.md

docs: update required spark and python version on website doc

---

website/docs/getting_started/installation.md

docs: update spark3.2 installation on Synapse

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/SynapseExtension/SynapseExtensionsTests.scala
pipeline.yaml

chore: re-enable E2E tests for Synapse-Extension

---

core/src/test/scala/com/microsoft/azure/synapse/ml/causal/VerifyDoubleMLEstimator.scala

#1820 
update test to cover the validation of ATE value, ensures we don't have a flipped treatment effect.

test: Update test to validate ATE value should be positive with the test data

---

cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/anomaly/MultivariateAnamolyDetectionSuite.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/face/FaceSuite.scala
notebooks/features/cognitive_services/CognitiveServices - Advanced Usage Async, Batching, and Multi-Key.ipynb

docs: Add a notebook for advanced cognitive service usage

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/SynapseTests.scala
pipeline.yaml

chore: turn off failing synapse tests

---

.github/workflows/scripts/clean-acr.py

#xxx
Correcting copy/paste error

chore: correct copy/paste error and add debugging print stmt

---

cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/form/FormRecognizerV3Suite.scala

chore: fix form recognition tests

---

notebooks/features/hyperparameter_tuning/HyperOpt-SynapseML.ipynb
notebooks/features/regression/Regression - Vowpal Wabbit vs. LightGBM vs. Linear Regressor.ipynb
notebooks/features/vw/Vowpal Wabbit - Overview.ipynb

#xxx
Replace Boston housing dataset by California housing dataset.
Manual, Compared evaluation metrics.

docs: replace boston housing dataset

---

notebooks/features/cognitive_services/CognitiveServices - Create Audiobooks.ipynb

docs: fix a few issues in cognitive service demo

---

CONTRIBUTING.md

fix: Correct syntax error in CONTRIBUTING.md

---

core/src/main/scala/com/microsoft/azure/synapse/ml/causal/DoubleMLEstimator.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/causal/DoubleMLParams.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/causal/VerifyDoubleMLEstimator.scala
website/docs/documentation/estimators/causal/_causalInferenceDML.md
website/yarn.lock

Fix bug #1869, and add colTyple and ModelType check

fix: bug #1869, DML .setFitIntercept should be set to true

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala
notebooks/features/cognitive_services/CognitiveServices - Create a Multilingual Search Engine from Forms.ipynb

docs: add custom chatbot creation to form demo

---

deep-learning/src/main/scala/com/microsoft/azure/synapse/ml/onnx/ONNXHub.scala

fix: Retry OnnxHub call to improve test reliability

---

notebooks/features/simple_deep_learning/DeepLearning - Deep Text Classification.ipynb
notebooks/features/simple_deep_learning/DeepLearning - Deep Vision Classification.ipynb

fix: generate random directory for each dnn test

---

build.sbt

#xxx
Upgrade LightGBM library to latest from Ilya. It has Dataset changes that we can use to optimize Spark usage (later PR).

feat: Update LightGBM version to 3.3.5

---

notebooks/features/regression/Regression - Vowpal Wabbit vs. LightGBM vs. Linear Regressor.ipynb

…pynb
N/A
Update the display call in an example notebook to remove .toPandas. This gets around a bug in notebookUtils.display
Externally tested

chore: Update call to display to remove .toPandas

---

cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/translate/TranslatorSuite.scala
tools/docker/demo/Dockerfile
tools/docker/minimal/Dockerfile

chore:  fix build issues

---

core/src/test/scala/com/microsoft/azure/synapse/ml/codegen/RTestGen.scala
environment.yml
tools/tests/run_r_tests.R

chore: fix r tests

---

notebooks/features/cognitive_services/CognitiveServices - OpenAI Embedding.ipynb
notebooks/features/cognitive_services/CognitiveServices - OpenAI.ipynb
website/versioned_docs/version-0.11.1/features/cognitive_services/CognitiveServices - OpenAI Embedding.md
website/versioned_docs/version-0.11.1/features/cognitive_services/CognitiveServices - OpenAI.md
website/versioned_sidebars/version-0.11.1-sidebars.json

docs: improve and organize openai docs

---

website/docs/reference/developer-readme.md

Adding a missing style check command for test projects.  The scala style check should run with the following command instead of "sbt test:scalastyle".
>>>sbt test:scalastyle
#xxx
Adding scala style check command for test project.
Not required.
- [*] No. You can skip this section.
- [*] No. You can skip this section.
5. …

chore: Update developer-readme.md (Scala Style Check)

---

deep-learning/src/main/python/synapse/ml/dl/LitDeepVisionModel.py

fix: add retries for torchvision download

---

deep-learning/src/main/python/horovod_installation.sh

chore: fix gpu notebook protobuf version

---

.github/workflows/on-pull-request-target-review.yml

ci: Add Azure Open AI based PR Summarization

---

README.md
website/docs/getting_started/installation.md
website/src/pages/index.js

docs: update spark33 installation instruction readme

---

pipeline.yaml

chore: add timeouts for R tests

---

notebooks/features/vw/Vowpal Wabbit - Classification using SparkML Vector.ipynb

spelling
NA
#xxx
Spelling changes
NA

docs: Update Vowpal Wabbit - Classification using SparkML Vector.ipynb

---

notebooks/features/vw/Vowpal Wabbit - Overview.ipynb

Update Vowpal Wabbit - Overview.ipynb

---

notebooks/features/vw/Vowpal Wabbit - Multi-class classification.ipynb

Update Vowpal Wabbit - Multi-class classification.ipynb

---

cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAIEmbeddingsSuite.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/io/split2/DistributedHTTPSuite.scala

chore: fix broken tests

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala

chore: exclude failing explanation dashboard notebook

---

templates/conda.yml

chore: retry conda install and add a timeout

---

pipeline.yaml
tools/tests/run_r_tests.R

chore: fix spark_install version

---

website/docs/features/lightgbm/about.md

Adjusted LightGBM docs for latest changes

docs: Add new LightGBM streaming docs

---

build.sbt
pipeline.yaml
project/Secrets.scala
project/plugins.sbt
sonatype.sbt

- Publishing the jar to ADO Maven Feed.
Verified that jar is published to ADO feed along with the blob storage

build: Publishing the jar to ADO Maven Feed

---

notebooks/features/cognitive_services/CognitiveServices - OpenAI.ipynb

docs: update OpenAI notebook

---

build.sbt
pipeline.yaml

build: upload notebooks to storage on every build

---

cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/form/FormRecognizerV3Suite.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/HTTPClients.scala
pipeline.yaml

fix: dont retry 4XX codes other than 429

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/geospatial/AzureMapsTraits.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/HTTPClients.scala

fix: make geospatial services robust to 404 thrown by the service

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala

chore: bump databricks e2e timeout

---

.github/workflows/check-dead-links.yml

docs: add dead link checker

---

docs/Explore Algorithms/AI Services/Advanced Usage - Async, Batching, and Multi-Key.ipynb
docs/Explore Algorithms/Anomaly Detection/Quickstart - Isolation Forests.ipynb
docs/Explore Algorithms/Hyperparameter Tuning/HyperOpt.ipynb
docs/Explore Algorithms/OpenAI/Quickstart - Understand and Search Forms.ipynb
website/src/pages/index.js

docs: continue fixing broken links

---

docs/Explore Algorithms/AI Services/Advanced Usage - Async, Batching, and Multi-Key.ipynb

docs: fix broken links

---

docs/Explore Algorithms/AI Services/Advanced Usage - Async, Batching, and Multi-Key.ipynb

docs: fix broken link

---

docs/Explore Algorithms/AI Services/Quickstart - Document Question and Answering with PDFs.ipynb

docs: variable formatting for QandA nb

---

website/docusaurus.config.js

chore: Add missing redirects to website

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala
docs/Explore Algorithms/Anomaly Detection/Quickstart - Isolation Forests.ipynb

chore: fix mlflow error in build

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/CognitiveServiceBase.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAICompletion.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAIPrompt.scala

Support using fabric mwc token to auth request to internal LLM endpoints

feat: support using mwc token for fabric openai transformer

---

core/src/main/scala/com/microsoft/azure/synapse/ml/logging/SynapseMLLogging.scala
core/src/test/scala/com/microsoft/azure/synapse/ml/logging/LoggingScrubberTests.scala
lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMBase.scala
vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitClassifier.scala
vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitContextualBandit.scala
vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitGeneric.scala
vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitRegressor.scala

chore: refactor telemetry system

---

cognitive/src/test/scala/com/microsoft/azure/synapse/ml/geospatial/AzureMapsSuite.scala

chore: fix geospatial tests

---

README.md

chore: Update README.md to avoid re-releasing

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/text/TextAnalytics.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/face/FaceSuite.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/text/TextAnalyticsSuite.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/translate/TranslatorSuite.scala
src/test/scala/com/microsoft/azure/synapse/ml/core/test/fuzzing/FuzzingTest.scala

chore: fix cognitive service tests

---

.github/workflows/on-pull-request-target-review.yml

#xxx
Fixing the gpt-review github action. See details [here](https://github.com/microsoft/gpt-review/issues/208#issuecomment-1763654379)

fix: gpt-review action

---

build.sbt
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/speech/SpeechAPI.scala
cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/speech/SpeechToTextSDK.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/speech/SpeechToTextSDKSuite.scala

chore: bump speech sdk version

---

docs/Explore Algorithms/AI Services/Advanced Usage - Async, Batching, and Multi-Key.ipynb
docs/Explore Algorithms/AI Services/Overview.ipynb
docs/Get Started/Quickstart - Your First Models.ipynb

docs: TextServiceAPI -> AnalyzeTextAPI

---

cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/text/TextAnalyticsSuite.scala
cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/translate/TranslatorSuite.scala
docs/Explore Algorithms/Causal Inference/Quickstart - Measure Causal Effects.ipynb
docs/Explore Algorithms/Causal Inference/Quickstart - Measure Heterogeneous Effects.ipynb

chore: fix failing tests

---

build.sbt

chore: Bump isolation forest to 3.0.4

---

README.md

chore: fix 1.0.1 version tags

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAI.scala

chore: update openai to latest API version

---

pipeline.yaml
templates/codecov.yml
templates/conda.yml
templates/kv.yml

chore: add retry logic to build steps

---

project/CodegenPlugin.scala

fix: Fix tag for pyCodeGenImpl

---

docs/Explore Algorithms/Hyperparameter Tuning/HyperOpt.ipynb

chore: fix flaky HyperOpt NB

---

pipeline.yaml

chore: add more retries to build steps

---

pipeline.yaml

chore: add more build retries

---

docs/Explore Algorithms/Classification/Quickstart - Train Classifier.ipynb

chore: fix synapse notebook demo

---

docs/Explore Algorithms/OpenAI/OpenAI.ipynb

https://github.com/microsoft/SynapseML/blob/master/docs/Explore%20Algorithms/OpenAI/OpenAI.ipynb 
#PingMSFTDocs
#xxx
6. Make sure the `WebsiteSamplesTests` job pass …

Update OpenAI.ipynb (Typo "Azure Open AI"→"Azure OpenAI")

---

templates/conda.yml

chore: stop conda from using --force

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala

chore: give tests more time

---

core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala
environment.yml

chore: improve test reliability

---

pipeline.yaml

chore: fix conda caching in builds

---

cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/geospatial/AzureMapsSuite.scala

chore: fix azure maps tests

---

core/src/main/python/synapse/ml/core/logging/SynapseMLLogger.py
core/src/main/scala/com/microsoft/azure/synapse/ml/logging/SynapseMLLogging.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/logging/fabric/CertifiedEventClient.scala

chore: fix certified events emitting

---

docs/Explore Algorithms/Hyperparameter Tuning/HyperOpt.ipynb
docs/Explore Algorithms/Regression/Quickstart - Vowpal Wabbit and LightGBM.ipynb
docs/Explore Algorithms/Vowpal Wabbit/Quickstart - Classification, Quantile Regression, and Regression.ipynb

chore: eliminate sklearn datasets dep

---

pipeline.yaml

chore: fix github release yml

---

environment.yml
pipeline.yaml
templates/free_up_space.yml

chore: free up space on build machines prior to caching

---

templates/conda.yml

We perform the cleanup regardless of using cached conda environment or not
This is for pipeline, unit test not possible

chore: Trying to fix the space problem

---

pipeline.yaml

chore: fix yml

---

project/build.properties

chore: update sbt version to allow for amd local builds

---

.devcontainer/devcontainer.json
.devcontainer/postCreate.sh

Adds a devcontainer configuration to help standardize development in vscode.
> Note: You may need to run a `Clean Compile` in Metals and wait for compilation before tests appear

chore: Add devcontainer configuration for vscode and Copilot

---

cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/CognitiveServiceBase.scala
core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/HTTPSchema.scala

chore: fix propagation of fabric telemetry
