microsoft/SynapseML

- tools/deployment/azureDeployMainTemplate.json
- tools/deployment/gpuVmExistingVNetTemplate.json
Azure can only works with the "raw.githubusercontent.com" links to GitHub items referenced in an ARM template. For example,
https://github.com/Azure/azuremls/blob/master/tools/deployment/sparkClusterInVnetTemplate.json 
needs to be changed to
https://raw.githubusercontent.com/Azure/mmlspark/master/tools/deployment/sparkClusterInVnetTemplate.json
> Update GitHub urls referenced in ARM templates with the raw.githubusercontent.com ones

- src/clean-missing-data/build.sbt
- src/clean-missing-data/src/main/scala/CleanMissingData.scala
- src/clean-missing-data/src/test/scala/VerifyCleanMissingData.scala
- src/core/contracts/src/main/scala/Params.scala
Add clean missing data module with modes:
1.) Replace with mean - replaces missings with mean of fit column 
2.) Replace with median - replaces missings with approximate median of fit column 
3.) Replace with custom value - replaces missings with custom value specified by user
As well as several smoke tests
Also added HasInputCols and HasOutputCols as traits for multiple columns (which will be needed when imputation will be added).
Resolved issue: Add support for missing value cleaner  #11
> Add clean missing data module

- README.md
- tools/build-pr/report
- tools/build-pr/shared.sh
- tools/config.sh
- tools/runme/build.sh
* Add items to `Build.md` when uploading the maven and pip packages,
when publishing to the demo cluster, and when pushing a new docker
image.
* Upload Build.md to the main buildartifacts container so the updated
information with all of the above is easily available.
* Verify azure login before any publishing happens.
* Misc minor tweaks.
> Improve `Build.md` and a few other things

- src/codegen/src/main/scala/PySparkWrapper.scala
- src/codegen/src/main/scala/WrapperClassDoc.scala
- src/core/contracts/src/main/scala/Params.scala
- src/core/schema/src/main/python/TypeConversionUtils.py
- src/core/schema/src/main/python/Utils.py
- src/downloader/src/main/python/ModelDownloader.py
- src/readers/src/main/python/ImageReader.py
- src/value-indexer/src/main/scala/ValueIndexer.scala
- Parameterized indentation in formatted string that had multiple
spaces (i.e. "        some text" became "${ScopeDepth}some text")
- removed unnecessary blank lines in custom python scripts
- added docstrings and scaladocs for ValueIndexer
- corrected typos
> Documentation corrections and updates

- src/codegen/src/main/scala/DocGen.scala
Class names are capitalized when the PySpark wrappers are generated.
Therefore, it is unnecessary to capitalize again when generating
.rst files for documentation from the python wrappers.
> Docgen correction

- tools/bin/mml-exec
- tools/runme/utils.sh
I couldn't find any way to configure spark to avoid caching mmlspark in
ivy2, so instead just look for all files with the version string and
clear them out.  Do this in `mml-exec` since this is where such a spark
configuration would normally go.
Also fix some leftover code that resulted in two ".local"s in the
version.
> Clear the ivy cache of mmlspark when running a local build

- tools/docker/bin/launcher
Keep some of the error message, so people can skip it early, or in case
launching the python web server fails for whatever reason.
Use `microsoft/mmlspark:0.4.5` to try it out.
> Re-enable the docker EULA server

- CONTRIBUTING.md
- docs/your-first-model.md
It looks very redundant to repeat it in every text... so I think that
it's fine to leave on in the toplevel `README.md`.
> Remove copyrights footnotes, except from `README.md`

- tools/hdi/install-mmlspark.sh
1. There was a build failure which we tracked down to a situation there
was a build of "0.5.dev29+1.geccd8f6" followed by a build of
"0.5.dev29" -- and in the second one, pip decided that "Requirement
already satisfied" which meant that it was using the earlier version.
To avoid that, explicitly uninstall "mmlspark" to always get rid of
other versions.
2. While tracking that, we found another bug where `$condaenv` was used
instead of `$env`.  This meant that we would always install (twice)
to the environment last specified in `$condaenv` which happened to be
`py35`, the one that is actually used in the E2E tests.
3. It shouldn't matter in general, but I also moved the pip installation
to happen before the dummy spark job that installs the mmlspark
package.
> Fix the pip installation on a cluster

- src/cntk-train/src/test/scala/ValidateCntkTrain.scala
- src/codegen/src/main/scala/CodeGen.scala
- src/core/env/src/main/scala/FileUtilities.scala
- src/downloader/src/test/scala/DownloaderSuite.scala
- src/featurize/src/test/scala/VerifyFeaturize.scala
- src/find-best-model/src/test/scala/VerifyFindBestModel.scala
- src/fuzzing/src/test/scala/Fuzzing.scala
- src/image-transformer/src/test/scala/ImageTransformerSuite.scala
- src/train-classifier/src/test/scala/VerifyTrainClassifier.scala
- src/train-regressor/src/test/scala/VerifyTrainRegressor.scala
Instead, use `commons.io.FileUtils.forceDelete` which is similar except
that it throws an error if the given path does not exist.
Supersedes #53.
> Remove our `delTree`

- tools/misc/container-gc
Mainly avoid deleting files from `1.2.dev40/...` when `1.2.dev4` is
collected.
> Fix the `container-gc` script

- tools/bin/mml-exec
- tools/runme/build.sh
- tools/runme/utils.sh
1. Checking which tag `master` is on doesn't work with the VSTS builds
since it doesn't update `master`.  Use `$branch` instead.
2. Avoid clearing the ivy cache if `$HOME/.ivy2` doesn't exist.
3. Remove a possible `\n` in the keyvault value.
> Minor script fixes

- src/cntk-train/src/test/scala/ValidateDataConversion.scala
This is a fix for issue:
https://github.com/Azure/mmlspark/issues/90
One of the test cases was not removing a temporary directory.
> Added clean up code after test case

- src/cntk-train/src/main/scala/BrainscriptBuilder.scala
- src/cntk-train/src/main/scala/CommandBuilders.scala
- src/codegen/src/main/scala/PySparkWrapper.scala
- src/core/serialize/src/main/scala/params/ByteArrayParam.scala
Updating CNTKLearner to work with latest gpu branch updated with latest master.
Removed setting owner, fixed ByteArrayParam transfer from java to python, fixed path to model.
Verified full end-to-end scenario.
> Updating CNTKLearner to work with latest gpu branch updated with latest master

- src/codegen/src/main/scala/CodeGen.scala
- src/codegen/src/main/scala/PySparkWrapper.scala
- src/core/schema/src/main/python/TypeConversionUtils.py
- src/core/schema/src/main/python/Utils.py
-fix a problem where internal wrappers could not be serialized
-fix a problem where byte array params were not transferred to python properly
> Fix Pyspark Wrapper Generation

- src/readers/src/main/scala/BinaryFileReader.scala
Performance improvement for BinaryFileReader and ImageReader.
Temporary fix around bug introduced in spark 2.1 (from spark 2.0).
Validated performance improvement on Mark's demo cluster (previously would not finish, afterwards would take a couple minutes/seconds for operations).
> Performance improvement for BinaryFileReader and ImageReader

- tools/config.sh
- tools/misc/container-gc
- tools/misc/get-stats.js
`container-gc`:
* Set `$AZURE_STORAGE_KEY`, which prevents the CLI from getting it using
the API -- which has caused very frequent throttling failures.
* Auto-delete version infos that might have been made during a
build (and therefore they can be outdated).
* Sleep much less before deletions start.
* Add a "refresh" option to refresh an info file.
`get-stats.js`:
* Use a specific environment variable for the stats storage access,
since the azure function is now on its own container.
Most of these were motivated by API throttling issues.
> Fixes related to using the azure storage CLI

- tools/misc/container-gc
- tools/pydocs/publish
- tools/runme/build.sh
- tools/runme/runme.sh
- tools/runme/utils.sh
Most (hopefully all) of our API throttling issues were a result of the
CLI retrieving the subscription information each time it starts.  This
can be avoided by retrieving it once and setting `$AZURE_STORAGE_KEY` to
it.
(Note that this is done lazily, when `az` is first used.)
> Resolve throttling issue

- tools/runme/utils.sh
This allows building tags that are on a branch other than `master`.
> Don't add commit number indicator to version when building a tag

- tools/notebook/tester/TestNotebooksOnHdi.py
For some reason, the hdi setup started producing a 2-tuple with the
expected list in the second place, no idea why, so make the code handle
both cases.
> Fix handling of the result of `run_cell`

- src/readers/src/main/scala/ImageReader.scala
- src/readers/src/test/scala/BinaryFileReaderSuite.scala
- src/readers/src/test/scala/ImageReaderSuite.scala
- It now sets the field to None when it encounters corrupt images
> Fix behavior of ImageReader for corrupt images

- src/core/serialize/src/main/scala/Serializer.scala
- src/train-classifier/src/test/scala/VerifyTrainClassifier.scala
This PR fixes the issue here:
https://github.com/Azure/mmlspark/issues/133
It looks like disposing the file system object was removing the currently set working directory and all other temporary settings, and a new file system object was getting created from the Hadoop configuration.
> Changed save code to not modify the current working directory by removing the code that disposed the current file system

- tools/config.sh
- tools/hdi/install-mmlspark.sh
- tools/hdi/setup-test-authkey.sh
- tools/misc/container-gc
- tools/runme/build.sh
- tools/runme/install.sh
- tools/runme/utils.sh
* When `CNTK_WHEELS` isn't specified for an environment, ignore it
instead of failing.
* `defvar` has a new `-X` flag for variables that are all injected into
generated scripts (currently only the HDI scripts).
* Use this to generate the HDI scripts instead of listing each value
that is to be replaced.  (It also makes it easier to maintain since
they use the same variable names as the rest of the runme scripts.)
* Fix the version sorting in container-gc, so no versions are
dropped (using 1,2 includes the second key (after the `#`) so it gets
considered for uniqueness too).
> Script fixes and improvements

- notebooks/samples/302 - Pipeline Image Transformations.ipynb
- src/cntk-model/src/main/scala/CNTKModel.scala
- src/core/env/src/main/scala/StreamUtilities.scala
- src/core/hadoop/src/main/scala/HadoopUtils.scala
- src/core/schema/src/main/scala/BinaryFileSchema.scala
- src/core/schema/src/main/scala/ImageSchema.scala
- src/core/test/base/src/main/scala/TestBase.scala
- src/featurize/src/main/scala/AssembleFeatures.scala
- src/image-featurizer/src/test/scala/ImageFeaturizerSuite.scala
- src/image-transformer/src/main/scala/ImageTransformer.scala
- src/image-transformer/src/main/scala/UnrollImage.scala
- src/readers/src/main/python/BinaryFileReader.py
- src/readers/src/main/python/ImageReader.py
- src/readers/src/main/scala/BinaryFileFormat.scala
- src/readers/src/main/scala/BinaryFileReader.scala
- src/readers/src/main/scala/ImageFileFormat.scala
- src/readers/src/main/scala/ImageReader.scala
- src/readers/src/main/scala/Readers.scala
- src/readers/src/test/scala/BinaryFileReaderSuite.scala
- src/readers/src/test/scala/ImageReaderSuite.scala
- Replace old readers with new performant Dataframe readers
- Remove all references to DF.rdd.mapPartitions
> Refactor MMLSpark for Structured Streaming

- tools/misc/expunge
- tools/runme/build.sh
- tools/runme/utils.sh
* `call_ifdef` needs to restore the working directory, without that
`Spark.setup` would mess up the directory for `Spark.init` making it
unable to find the Python zip files.
* When removing jars of other versions, make sure to not delete jars
like `mmlspark_2.11-$ver-{javadoc,sources}.jar`.
> Minor build fix

- tools/notebook/postprocess.py
When there is any error message in the loading of notebooks from notebooks/samples/ the error message was related to the contents of the file instead of the file name.
The change improves the error message when failing to Decode notebook JSON by adding the file name to the error message.
> Add file name to notebook JSON decoding errors

- README.md
- docs/docker.md
- tools/build-pr/report
- tools/misc/mmlspark.svg
* Switch to using `mmlspark.svg`, so it looks better.  Including a new
SVG that can scale.
* Switch the build status icons to SVGs, with a standard text-label
below the robot face.
* Add a release notes link, use an SVG button-like image so it can float
right.
* Also bump the hard-wired version for the upcoming v0.9 release.
> Tweak README and icons

- notebooks/samples/103 - Before and After MMLSpark.ipynb
- tools/config.sh
- tools/misc/container-gc
- tools/pydocs/build
- tools/runme/build.sh
- tools/runme/utils.sh
* Hack around the problem of running sbt in bash: sbt uses a newer jline
version and it doesn't restore some tty settings.  Use stty to
properly restore them -- and add a check that will throw an error when
we update to a newer version since this problem should be resolved in
an upcoming version.
* Improve substitutions of `<{var}>` in delayed variables, and extend
them with bash variable substitutions.
* Improve `<{ver}>` substitutions in INSTALLATION entries using the
above, so now they work with any keys and include bash substitutions.
* For CNTK installation, use the "version.txt" file in the root to
verify the installed version, instead of the previous hack.
* Make `container-gc` account for the R container.
* `pydocs/build`: use `_mcd` instead of `cd` to make the pyspark doc dir …
> Some build and other script fixes

- src/readers/src/main/scala/BinaryFileFormat.scala
- src/readers/src/main/scala/ImageFileFormat.scala
- src/readers/src/main/scala/KeyValueReaderIterator.scala
- src/readers/src/test/scala/ImageReaderSuite.scala
Fixing image reader so that path in schema would contain the full path to image (or file) instead of just the zip file and added a test to validate
> Fixing reader to display full path to image

- tools/bin/mml-exec
- tools/build-pr/checkout
- tools/build-pr/shared.sh
- tools/config.sh
- tools/docker/bin/eula
- tools/misc/container-gc
- tools/runme/install.sh
- tools/runme/utils.sh
* Fix a bug that was introduced in f1704d3: translations of the old
`setenv` into `defvar -e` should have used the -f flag to force the
values.  This bug would lead to the problem of "sticky" versions that
don't change.  Make `-e` imply `-f`, which also makes sense since if
we're changing a user's profile then we need to force a change of
whatever is currently there.
* `container-gc`: use a file for collecting info, to avoid getting
errors about going over the shell limits.
* Some more bash-isms.
> A few more build/script fixes

- tools/runme/utils.sh
A bug in the revised code would fail to add the first installer name.
> Fix `_parse_install_info`

- tools/build-pr/checkout
- tools/build-pr/shared.sh
- tools/runme/utils.sh
* Throw a good error message when given a bad PR number.
* Also throw an error message when given a closed PR number (could allow
it, but the PR branch is likely deleted anyway).
* cd into `$BASEDIR` before using `git` to get the build info.
> More script fixes

- notebooks/samples/202 - Amazon Book Reviews - Word2Vec.ipynb
- src/clean-missing-data/src/main/scala/CleanMissingData.txt
- src/codegen/src/main/scala/PySparkWrapper.scala
- src/compute-model-statistics/src/main/scala/ComputeModelStatistics.txt
- src/compute-per-instance-statistics/src/main/scala/ComputePerInstanceStatistics.txt
- src/data-conversion/src/main/scala/DataConversion.txt
- src/summarize-data/src/main/scala/SummarizeData.txt
- src/train-classifier/src/main/scala/TrainClassifier.txt
Some docstrings did not format correctly on the Pyspark doc pages due
to missing blank lines. Added the blank lines back in to make the
documentation pages pretty again.
Corrected typo in title of notebook.
> Documentation formatting corrections

- notebooks/samples/104 - Price Prediction Regression Auto Imports.ipynb
- notebooks/samples/105 - Regression with DataConversion.ipynb
Sample notebooks 104, which is based on Sample 6 from the Studio AzureML Gallery, and 105, which is an alternate version of 102. These notebooks demonstrate MMLSpark APIs which haven't appeared in other sample notebooks.
> Initial sample notebooks additions

- tools/build-pr/checkout
- tools/build-pr/report
- tools/misc/container-gc
1. Show the SHA1 in GH build comments, to make it easy to identify
failed builds.
2. Wider printout of versions in container-gc.
> Misc tweaks

- src/readers/src/test/scala/PowerBiSuite.scala
Make them use `Extended` in addition to `BuildServer`, so they're not
used in a normal dev build.
Fixes #201.
> Fix PowerBI tests

- src/compute-model-statistics/src/main/scala/ComputeModelStatistics.scala
- src/compute-model-statistics/src/test/scala/VerifyComputeModelStatistics.scala
- src/compute-per-instance-statistics/src/main/scala/ComputePerInstanceStatistics.scala
- src/compute-per-instance-statistics/src/test/scala/VerifyComputePerInstanceStatistics.scala
- src/core/contracts/src/main/scala/Params.scala
- src/core/metrics/build.sbt
- src/core/metrics/src/main/scala/MetricConstants.scala
- src/core/metrics/src/main/scala/MetricUtils.scala
- src/find-best-model/src/main/scala/EvaluationUtils.scala
- src/find-best-model/src/main/scala/FindBestModel.scala
- src/find-best-model/src/test/scala/VerifyFindBestModel.scala
- src/tune-hyperparameters/src/main/scala/TuneHyperparameters.scala
- src/tune-hyperparameters/src/test/scala/VerifyTuneHyperparameters.scala
Updating per instance stats module to work for spark ML estimators in addition to TrainClassifier and TrainRegressor.
Also doing some minor refactoring and removing duplicate code.
> Updating per instance stats module to work for spark ML estimators in addition to TrainClassifier and TrainRegressor

- notebooks/samples/104 - Price Prediction Regression Auto Imports.ipynb
- src/compute-model-statistics/src/main/scala/ComputeModelStatistics.scala
- src/compute-model-statistics/src/test/scala/VerifyComputeModelStatistics.scala
CMS sometimes gets randomly stuck in catalyst when dropping missing values if a specific sequence of estimators is run before it.  Caching the data resolves the issues with catalyst.  This looks like a bug in spark's catalyst which might have been already resolved in future versions of spark.
This resolves issue #186
> Fixing random performance bug in CMS due to catalyst issue

- tools/build-pr/checkout
- tools/build-pr/report
- tools/build-pr/shared.sh
- tools/misc/container-gc
It is now possible to use `<user>/<repo>/<branch>` for the "BuildPR"
field.  These were called "private builds" when implemented a few
commits ago as a quick hack.
> Improve branch builds

- README.md
Updated the Databricks instructions to directly use the Spark package Maven Coordinates instead of our own Maven repo. Fixes issue #250
> Fix Databricks instruction

- tools/config.sh
this fixes a customer issue with the docker where importing numpy causes an error, the error seems to be related to the libmkl_rt.so file being missing.
> keep mkl so file

- docs/mmlspark-serving.md
Adds the missing import which completes hello world example for pyspark serving
> Add missing import length in PySpark Serving Docco

- src/compute-model-statistics/src/main/scala/ComputeModelStatistics.scala
- src/compute-model-statistics/src/test/scala/VerifyComputeModelStatistics.scala
- src/core/metrics/src/main/scala/MetricConstants.scala
Improving performance on multiclass data when there is a large number of labels in the dataset
> Fixing CMS multiclass performance and adding tests

- src/lightgbm/src/main/python/LightGBMClassifier.py
- src/lightgbm/src/main/scala/LightGBMBooster.scala
- src/lightgbm/src/main/scala/LightGBMClassifier.scala
- src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
This PR is to implement the functionality of save_model() for LightGBM model's booster. It serialize the model into the string representation the same way as scikit-learn implememtation (https://github.com/Microsoft/LightGBM).
When calling save_booster() from pyspark or saveBooster() from scala, the filename could be either local or WASB URI.
This should address Issue #294
> LightGBM model save model function

- src/lightgbm/src/main/scala/LightGBMClassifier.scala
- src/lightgbm/src/main/scala/LightGBMParams.scala
- src/lightgbm/src/main/scala/LightGBMRegressor.scala
- src/lightgbm/src/main/scala/LightGBMUtils.scala
- src/lightgbm/src/main/scala/TrainUtils.scala
We now determine the number of CPUs per executor (where 1 executor = 1 JVM).
On the driver, we start a separate thread prior to calling LightGBM train which waits to receive the (host,port) from (# executors X # cores) workers.
Prior to network init, on each of the workers we allocate a port and send it to the driver thread.
The driver thread receives all ports, aggregates, and then sends back the result so it can be used for network init.
This resolves several issues - 
1.) we ensure that the ports selected are open (we find only "open" ports and bind to them)
2.) we discover the number of CPUs per executor (per JVM) and use that - and all workers now request a port
3.) better logging to detect problems
This resolves issue: https://github.com/Azure/mmlspark/issues/292
> Improving performance of LightGBM for cluster with multiple cores per executor

- src/lightgbm/src/main/scala/LightGBMBooster.scala
Discussed in https://github.com/Azure/mmlspark/issues/315, the merge function doesn't need anymore. Would better to remove it.
> Remove LightGBMBooster's mergeModels function

- src/lightgbm/src/main/scala/LightGBMClassifier.scala
- src/lightgbm/src/main/scala/LightGBMRegressor.scala
- src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
- src/lightgbm/src/test/scala/VerifyLightGBMRegressor.scala
fixing copy method and verifying LGBM can be run with train TrainValidationSplit
this resolves issue #329 
Note the copy doesn't actually do anything - it is just needed because we don't have a constructor that takes in only a uid and nothing else (which spark transformers all have).  But this doesn't actually make sense to do, as none of the parameters on the model should be modifiable.
> fixing copy method and verifying LGBM can be run with train TrainValidationSplit

- src/lightgbm/src/main/scala/LightGBMClassifier.scala
- src/lightgbm/src/main/scala/LightGBMRegressor.scala
This is useful for getting internal information from the booster, such as the string representation.
> Added getter for LightGBMBooster

- notebooks/samples/106 - Quantile Regression with LightGBM.ipynb
- src/lightgbm/src/main/scala/LightGBMBooster.scala
- src/lightgbm/src/main/scala/LightGBMClassifier.scala
- src/lightgbm/src/main/scala/LightGBMParams.scala
- src/lightgbm/src/main/scala/LightGBMRegressor.scala
- src/lightgbm/src/main/scala/TrainParams.scala
- src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
* Add numClasses and objective in params
* Infer actualNumClasses from objective since native code for getting numClasses is always 1 unless it is multi-class classification problem. This is useful if we need to know the actual number of classes used during training. Removed `LightGBMBooster.numClasses` since it's not useful at all
* Change "application" to "objective" in regressor to consolidate params in both regressor and classifier
> Added numClasses and objective, infer actualNumClasses from objective

- notebooks/samples/203 - Breast Cancer - Tune Hyperparameters.ipynb
- src/codegen/src/main/scala/WrapperGenerator.scala
- src/lightgbm/src/main/python/LightGBMClassifier.py
- src/lightgbm/src/main/python/LightGBMRegressor.py
- src/tune-hyperparameters/src/main/python/TuneHyperparameters.py
- src/tune-hyperparameters/src/main/scala/TuneHyperparameters.scala
Adding getBestModel and getBestModelInfo to TuneHyperparametersModel (python API)
> Adding getBestModel and getBestModelInfo to TuneHyperparametersModel

- README.md
- docs/lightgbm.md
[JPMML-SparkML-LightGBM](https://github.com/alipay/jpmml-sparkml-lightgbm) plugin is now open-sourced. Here we cross reference each other.
> Cross reference jpmml-sparkml-lightgbm plugin

- src/lightgbm/src/main/scala/LightGBMUtils.scala
We should use a combination of spark conf and number of cores per machine via java.lang.Runtime.getRuntime.availableProcessors to figure out the number of cores per executor.
Fixed based on discussion here: https://github.com/Azure/mmlspark/issues/379
Thank to @humbinal for figuring out how to fix the issue.
Also should resolve the issue brought by @ywskycn here: https://github.com/Azure/mmlspark/issues/346
Note: This may be eventually resolved in a better way with spark's barrier execution mode when it is implemented aka project hydrogen (without needing to compute num cores):
https://jira.apache.org/jira/browse/SPARK-24374
> use conf to get num cores per executor

- src/lightgbm/src/main/scala/LightGBMBooster.scala
- src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
- src/lightgbm/src/test/scala/VerifyLightGBMRegressor.scala
fix for off-by-one error noticed by a data scientist when getting feature importances from lightgbm + tests
> fix off by one error on feature importances length

- src/lightgbm/src/main/scala/LightGBMClassifier.scala
- src/lightgbm/src/main/scala/LightGBMParams.scala
- src/lightgbm/src/main/scala/LightGBMRegressor.scala
- src/lightgbm/src/main/scala/LightGBMUtils.scala
- src/lightgbm/src/main/scala/TrainParams.scala
- src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
- src/lightgbm/src/test/scala/VerifyLightGBMRegressor.scala
resolves issue #367 
This actually does two things:
1.) We natively and automatically pass to lightgbm any columns that have been string-indexed as categoricals
2.) We have a parameter to allow user to manually specify the categorical columns
> Added categorical column support to LightGBM

- src/core/schema/src/main/scala/Categoricals.scala
- src/lightgbm/src/main/scala/LightGBMClassifier.scala
- src/lightgbm/src/main/scala/LightGBMParams.scala
- src/lightgbm/src/main/scala/LightGBMRegressor.scala
- src/lightgbm/src/main/scala/LightGBMUtils.scala
- src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
- src/lightgbm/src/test/scala/VerifyLightGBMRegressor.scala
fixes issue https://github.com/Azure/mmlspark/issues/367
the previous fix was actually incorrect because it was for columns and not slots on the features column (very bad mistake!)
the user can now specify either the slot index within the vector features column or the slot name (but the slot name may not always be there, eg for sparse case it is removed in FastVectorAssembler to prevent OOM on very sparse data)
> fix categorical handling logic to use slot names and indexes

- src/lightgbm/src/main/scala/LightGBMParams.scala
resolves issue mentioned here:
https://github.com/Azure/mmlspark/issues/379#issuecomment-454252196
for larger datasets we hit the timeout limit, it seems prudent to increase it
> increase default timeout

- notebooks/samples/HyperParameterTuning - Fighting Breast Cancer.ipynb
- src/tune-hyperparameters/src/main/python/HyperparamBuilder.py
resolves issue https://github.com/Azure/mmlspark/issues/473
HyperParam builder will now return a dictionary from param to (estimator, hyperparam), which is similar to parammap structure (parammap is dictionary from param to value but we can't quite do the same since we have a value generator and we need the estimator later on to extract the java param).
FYI @yueguoguo
> return list of param name to estimator and param from hyperparam builder

- src/lightgbm/src/main/scala/LightGBMConstants.scala
- src/lightgbm/src/main/scala/LightGBMUtils.scala
- src/lightgbm/src/main/scala/TrainUtils.scala
- src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
Fix bug causing LightGBM to hang until timeout when there are empty partitions
In the case that there are empty partitions we just ignore them and log a warning.  We prevent those workers from being included in NetworkInit.
Previously, we would just hang until timeout (network refused errors) because some workers would exit early while others would get stuck in UpdateOneIter waiting for them.
Also added additional debug to make it easier to keep track of when workers enter UpdateOneIter method (since that seems to be the case where they get stuck the most, when trying to sync with other workers).
> Fix bug causing LightGBM to hang until timeout when there are empty partitions

- src/lightgbm/src/main/scala/LightGBMBase.scala
- src/lightgbm/src/main/scala/LightGBMClassifier.scala
- src/lightgbm/src/main/scala/LightGBMParams.scala
- src/lightgbm/src/main/scala/LightGBMRegressor.scala
- src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
Resolves user request to add batch training to lightgbm on clusters with lower memory (note: not listed in issues)
User can now specify the number of batches (must be > 0) if they want to enable batch training.
> add batch training support in lightgbm classifier and regressor

- src/lightgbm/src/main/scala/LightGBMClassifier.scala
- src/lightgbm/src/main/scala/LightGBMParams.scala
- src/lightgbm/src/main/scala/LightGBMRanker.scala
- src/lightgbm/src/main/scala/LightGBMRegressor.scala
- src/lightgbm/src/main/scala/TrainParams.scala
- src/lightgbm/src/main/scala/TrainUtils.scala
In LightGBM CLI binary, there is an useful config parameter named `is_provide_training_metric`. If it is turned on, all defined metrics for training data are printed after each iteration like:
```
[LightGBM] [Info] Iteration:1, training auc : 0.973625
[LightGBM] [Info] Iteration:1, training binary_logloss : 0.252878
[LightGBM] [Info] 5.466509 seconds elapsed, finished iteration 1
[LightGBM] [Info] Iteration:2, training auc : 0.98312
[LightGBM] [Info] Iteration:2, training binary_logloss : 0.185529
[LightGBM] [Info] 11.769265 seconds elapsed, finished iteration 2
```
These messages are extremely helpful when drawing metric curves during training.
However, it won't work if we pass `is_provide_training_metric` to LightGBM as a config parameter. Because this parameter is only consumed in the …
> [LightGBM] Implement `is_provide_training_metric` in Scala codes through JNI.

- src/lightgbm/src/main/scala/LightGBMBase.scala
- src/lightgbm/src/main/scala/LightGBMUtils.scala
- src/lightgbm/src/main/scala/TrainUtils.scala
fixes several issues found by an internal data scientist when running lightgbm:
1.) reduce memory usage and execution time by selecting only relevant columns prior to calling mapPartitions in training
2.) fix frozen jobs if spark.task.cpus > 1 (driver expects more workers than it gets)
3.) add more debug logging for dataset format
> reduce memory usage in lightgbm, fix frozen jobs, add more debug logging

- docs/lightgbm.md
- src/lightgbm/src/main/scala/LightGBMBase.scala
- src/lightgbm/src/main/scala/LightGBMConstants.scala
- src/lightgbm/src/main/scala/LightGBMParams.scala
- src/lightgbm/src/main/scala/LightGBMUtils.scala
- src/lightgbm/src/main/scala/TrainUtils.scala
- src/lightgbm/src/test/scala/VerifyLightGBMClassifier.scala
By default LightGBM uses regular spark paradigm for launching tasks and communicates with the driver to coordinate task execution.
The driver thread aggregates all task host:port information and then communicates the full list back to the workers in order for NetworkInit to be called.
There have been some issues on certain cluster configurations because the driver needs to know how many tasks there are, and this computation is surprisingly non-trivial in spark.
With the next v0.18 release there is a new UseBarrierExecutionMode flag, which when activated uses the barrier() stage to block all tasks.
The barrier execution mode simplifies the logic to aggregate host:port information across all tasks, so the driver will no longer need to precompute the number of tasks in advance.
To use it in …
> adding barrier execution mode to lightgbm learners

- build.sbt
- src/main/scala/com/microsoft/ml/spark/vw/VowpalWabbitBase.scala
- src/main/scala/com/microsoft/ml/spark/vw/VowpalWabbitClassifier.scala
- src/test/scala/com/microsoft/ml/spark/vw/VerifyVowpalWabbitClassifier.scala
fixes #642 
updates to latest VW (required for link logistic fix)
fixes logistic regression unit test
> fix: Fix logistic regression error when passing "--link logistic"

- docs/cogsvc.md
@mhamilton723 adding a documentation page for using Cognitive Services on MMLSpark
> docs: Docs for Cognitive Services

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMConstants.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- src/main/scala/com/microsoft/ml/spark/stages/StratifiedRepartition.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
- src/test/scala/com/microsoft/ml/spark/stages/StratifiedRepartitionSuite.scala
fix for issues https://github.com/Azure/mmlspark/issues/609 and https://github.com/Azure/mmlspark/issues/569
> fix lightgbm stuck in multiclass scenario and added stratified repartition transformer

- docs/cogsvc.md
Per Sudarshan's suggestions...
> docs: Update to Cog Svc docs

- build.sbt
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBooster.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
update lightgbm to 2.2.400 - recently uploaded maven artifact of latest lightgbm build
includes fixes:
1.) Fix lightgbm swig wrapper on windows - now most windows tests will pass.  Not re-enabling windows tests yet because I am still seeing a test failure,but the majority of tests seem to pass now.
https://github.com/microsoft/LightGBM/pull/2364
2.) fix cached predictor causing bad probability values
https://github.com/microsoft/LightGBM/pull/2356
3.) exponential backoff for MPI ring connection, should improve test times significantly
https://github.com/microsoft/LightGBM/pull/2354
> fix: update lightgbm to 2.2.400, fix probabilities and some windows errors

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split2/VerifyLightGBMRanker.scala
for user request, to be able to use NDCG@N: https://github.com/Azure/mmlspark/pull/672
> feat: add eval_at parameter to lightgbm ranker

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
fix categorical handling on lightgbm learners
It seems that the categorical_feature parameter needs to be set on the dataset instead of the booster
resolves https://github.com/Azure/mmlspark/issues/665 and https://github.com/Azure/mmlspark/issues/660 
also opened a documentation defect here:
https://github.com/microsoft/LightGBM/issues/2398
> fix: categorical handling on lightgbm learners

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
created a new PR based on review for https://github.com/Azure/mmlspark/pull/688
fixes #682 based on user feedback
User may receive error that can be difficult to track down if they pass non-double column for label, weight or init score (int or long), so we just cast it to double for them if it is not already a double type column for convenience
> fix: cast errors for label, weight and init score columns

- src/main/scala/com/microsoft/ml/spark/core/utils/ClusterUtil.scala
fix num cores per executor if config not specified, improve logging
it seems the default for task CPUs if the config is not set is 1 instead of number of cores.  A bit surprising, as I was sure it was the other way around.
The spark docs seem to suggest it is indeed 1 by default though:
http://spark.apache.org/docs/latest/configuration.html
> fix num cores per executor if config not specified, improve logging

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
The description of labelGain hyper-parameter was not correct and has been corrected. Actually, it looked like the one corresponding to alpha hyper-parameter.
No change in behaviour. Just a small change in documentation
> docs: Change labelGain description

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBooster.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
I am not sure this is a fix, and not sure about the potential performance implications.
I think these changes could be helpful in solving memory issues that seem related to concurrency in spark such as https://github.com/microsoft/LightGBM/issues/2392.
Please feel free to comment, is just a proposal but I am not 100% sure that it fixes these issues.
> fix: Guarantee one boosterPtr is allocated and freed per LightGBMBooster instance

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBooster.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
fix: Possible multithreading issue when two scores may come in parallel they may not safely fill pointer values
Two threads can fill up scoredDataOutPtr in parallel and mix up their values
> fix: Possible multithreading issue when two scores may come in parallel they may not safely fill pointer values

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMDataset.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
added multiclass init score support
fixes issue https://github.com/Azure/mmlspark/issues/802
> fix: added multiclass init score support

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMDelegate.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRegressor.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
It is needed to monitor and hook in each training iteration.
It's because how well training my model and how much better metrics such as auc in each boost round.
contacts: keunhyun.oh@ahnlab.com
> feat: add delegate to monitor training

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMDelegate.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
Interface function is added for updating learning_rate per each iteration in LightGBMDelegate.
It is need if researcher want to decreasing or increasing learning rate per each boost round.
> feat: add interface function for updating learning_rate per each iteration in LightGBMDelegate

- build.sbt
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBooster.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMDataset.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
This includes a fix for a memory corruption issue:
https://github.com/microsoft/LightGBM/pull/3110
The new release has some major performance optimizations for the parallel distributed learner, training time and especially a major fix for a performance regression during scoring (3-4X):
https://github.com/microsoft/LightGBM/pull/2799
As well as a major fix for allocating more than max int array values per partition:
https://github.com/microsoft/LightGBM/pull/2859
This PR updates to LightGBM 2.3.180 on PR:
microsoft/LightGBM#3110
on commit:
microsoft/LightGBM@8ead7cc
> fix: updating lightgbm to 2.3.180

- src/main/python/mmlspark/lightgbm/LightGBMClassifier.py
- src/main/python/mmlspark/lightgbm/LightGBMRanker.py
- src/main/python/mmlspark/lightgbm/LightGBMRegressor.py
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBoosterParam.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMModelMethods.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRegressor.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split2/VerifyLightGBMRegressor.scala
unify APIs across LightGBM learner types and add SHAP feature importances to regressor
- Unify the APIs across regressor, ranker and classifier for predicting leaf index, getting global split/gini importances and getting local SHAP feature importances
- Add local SHAP feature importances to regressor
- Update pyspark API
Update:
- made models use ComplexParamsWritable based on PR comments
> feat: unify APIs across LightGBM learner types and add SHAP feature importances to regressor

- src/main/python/mmlspark/lightgbm/LightGBMClassifier.py
- src/main/python/mmlspark/lightgbm/LightGBMRanker.py
- src/main/python/mmlspark/lightgbm/LightGBMRegressor.py
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBooster.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMModelMethods.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
fixed SHAP values shape for multiclass case and improved pyspark API
tagging @ocworld for the multiclass classification SHAP values shape fix
> fix: fixed shap values shape for multiclass case and improved pyspark API

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
Reduce the network communication overhead cost in the reduce step for LightGBM learners (LightGBMClassifier, LightGBMRegressor and LightGBMRanker) by only returning the model from one of the nodes (determined by order of nodes initialized).  This is a small optimization that should slightly reduce the overall training time as well as make the code more robust by reducing overall network communication during reduce step.
> perf: reduce network communication overhead cost on reduce step for LightGBM learners

- src/main/scala/com/microsoft/ml/spark/core/utils/ClusterUtil.scala
- src/test/scala/com/microsoft/ml/spark/core/test/base/SparkSessionFactory.scala
- src/test/scala/com/microsoft/ml/spark/core/utils/VerifyClusterUtil.scala
This pr is fixing spark.executor.cores' default value based on master when counting workers.
The default value of spark.executor.cores is different as what master is.
It is 1 in YARN mode. In other case, It is all the available cores on the worker in standalone and Mesos coarse-grained modes.
(https://spark.apache.org/docs/latest/configuration.html)
Currently, I've tried to use mmlspark based on spark on k8s. When I did not set spark.executor.cores, error was occured. It is because not matched expected num of mmlspark workers with actual value.
> fix: spark.executor.cores' default value based on master when counting workers

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
Add num tasks override parameter for LightGBM learners
This parameter will allow users to override the default number of tasks that we try to calculate intelligently on their behalf.
Resolves part of issue:
https://github.com/Azure/mmlspark/issues/879
And issue:
https://github.com/Azure/mmlspark/issues/747
> feat: Add num tasks override parameter for LightGBM learners

- build.sbt
When iterating in a dev environment this ensures that it always overwrites the already installed version.
```
-I, --ignore-installed      Ignore the installed packages, overwriting them. This can break your system if the existing package is
of a different version or was installed with a different package manager!
```
> build: Ignore existing installation when running installPipPackageTask

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
fix for categorical parameter regression on dense dataset caused by missing whitespace
fixes issue https://github.com/Azure/mmlspark/issues/900
> fix: categorical parameter regression on dense dataset caused by missing whitespace

- src/main/python/mmlspark/lightgbm/LightGBMClassifier.py
- src/main/python/mmlspark/lightgbm/LightGBMRegressor.py
Currently `getFeatureShaps` does not work neither on dense vectors nor sparse ones.
For dense vectors `getDenseFeatureShaps` is not implemented.
But for sparse vectors error comes earlier: `vector.size` is `int` and should be passed further as it is.
This pull request fixes the error with processing field `size` of sparse vectors
> fix: Fix processing sparse vector size for getFeatureShaps

- build.sbt
Hi, the current 'master' branch can't upload 'whl' file to blob storage, the code missed 'mmlspark-'
> azure build pipeline hotfix

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMDataset.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- move lightgbm to new streaming API to reduce peak memory usage during distributed dataset creation
- although lightgbm memory usage reduction will differ depending on dataset, it should be around 50-70%
> perf: moving lightgbm to new streaming API for dense data to reduce memory usage

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
A customer reported constantly seeing "Remote RPC Client Disassociated" errors, we traced the issue to logging and the suggested fix here:
https://forums.databricks.com/questions/10616/executorlostfailure-remote-rpc-client-disassociate.html
to reduce logging, seemed to resolve the error.  Hitting the 20MB (that's MB, not GB!) limit in logging seems to cause this error, from the link:
> According to https://docs.databricks.com/jobs.html#jar-job-tips
>
> Job output, such as log output emitted to stdout, is subject to a 20MB size limit. If the total output has a larger size, the run will > be canceled and marked as failed.
> fix: reduce lightgbm verbosity to prevent RPC disassociated errors

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- tune chunking code, try to increase chunk size.  Difficult to say what ideal chunk size is, perhaps this should be parameter for user - although on the other hand, it's very easy for user to enter invalid value, and there are already so many parameters.
- fix memory leak missed in previous PR https://github.com/Azure/mmlspark/pull/1016 (labels, weights, init score need to be released)
> perf: tune chunking code, fix memory leak

- build.sbt
update to lightgbm jar 3.2.110 on commit:
https://github.com/microsoft/LightGBM/commit/1e95cb097757996cd82699071c82c205bf2b48a5
commit hash:
1e95cb097757996cd82699071c82c205bf2b48a5
resolves issue:
https://github.com/Azure/mmlspark/issues/986
with lightgbm fix:
https://github.com/microsoft/LightGBM/pull/4185
> chore: update to lightgbm 3.2.110

- src/main/python/mmlspark/lightgbm/LightGBMClassificationModel.py
- src/main/python/mmlspark/lightgbm/LightGBMRankerModel.py
- src/main/python/mmlspark/lightgbm/LightGBMRegressionModel.py
Missed adding returns to the new model methods for getting booster properties in recently merged PR https://github.com/Azure/mmlspark/pull/1024.  Also noticed some of them were calling the wrong underlying method when testing them out.
> fix: missing returns in new python lightgbm model methods

- src/main/python/mmlspark/lightgbm/LightGBMClassificationModel.py
- src/main/python/mmlspark/lightgbm/LightGBMRankerModel.py
- src/main/python/mmlspark/lightgbm/LightGBMRegressionModel.py
- src/main/python/mmlspark/lightgbm/mixin.py
add set methods to lightgbm models in pyspark APIs
resolves issue https://github.com/Azure/mmlspark/issues/721
Update: the original issue was fixed with new codegen, this PR now updates the python wrappers to use a common class
> fix: refactor python wrappers to use common class

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRegressor.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- add chunk size parameter for copying java data to native
- fix minor memory leak
- increase default chunk size from 1000 to 10000, for most real scenarios this is actually still probably more on the smaller side of what it should be set to (the number of rows in the dataset, but we don't want to do a count beforehand since it is expensive)
> feat: add chunk size parameter for copying java data to native

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRegressor.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
Add several parameters for dart mode as requested by two internal data scientists:
-  ``drop_rate``, default = ``0.1``, type = double, aliases: ``rate_drop``, constraints: ``0.0 <= drop_rate <= 1.0``
-  used only in ``dart``
-  dropout rate: a fraction of previous trees to drop during the dropout
-  ``max_drop``, default = ``50``, type = int
-  used only in ``dart``
-  max number of dropped trees during one boosting iteration
-  ``<=0`` means no limit
-  ``skip_drop``, default = ``0.5``, type = double, constraints: ``0.0 <= skip_drop <= 1.0``
-  used only in ``dart``
-  probability of skipping the dropout procedure during a boosting iteration
-  ``xgboost_dart_mode``, default = ``false``, type = bool
-  used only in ``dart``
-  set this to ``true``, if you want to use xgboost dart mode
- …
> feat: add several parameters related to dart boosting type

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRegressor.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
- add matrix type parameter to specify whether matrix is sparse, dense, or auto inferred
- allow user to override default auto logic to specify whether sparse or dense matrix must be constructed in lightgbm native code
- improve autologic to use first 10 sampled rows instead of just the head row when trying to determine whether constructed matrix should be sparse or dense
> feat: add matrix type parameter and improve auto logic

- scalastyle-config.xml
- scalastyle-test-config.xml
- src/main/scala/com/microsoft/lightgbm/SWIG.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMClassifier.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMDelegate.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMModelMethods.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRanker.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMRegressor.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/booster/LightGBMBooster.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/dataset/LightGBMDataset.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/params/FObjParam.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/params/FObjTrait.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/params/LightGBMBoosterParam.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/params/LightGBMParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/params/TrainParams.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/swig/SwigUtils.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split2/VerifyLightGBMRegressor.scala
add support for custom objective function in lightgbm learners
Users in the scala API will now be able to supply a custom loss function for training, which will need to output the gradient and hessian matrix.
As part of this PR, the LightGBMBooster and LightGBMDataset classes have been improved and moved under the booster and dataset folders, and some of the files related to parameters have been moved to a separate params folder in order to organize the code better since there are so many files in lightgbm directory.
TODO: add pyspark support, in a separate PR
> feat: add custom objective function to lightgbm learners

- src/main/scala/com/microsoft/ml/spark/nn/ConditionalKNN.scala
- src/main/scala/com/microsoft/ml/spark/nn/KNN.scala
- src/main/scala/org/apache/spark/sql/types/injections/OptimizedCKNNFitting.scala
- src/test/scala/com/microsoft/ml/spark/nn/BallTreeTest.scala
- src/test/scala/com/microsoft/ml/spark/nn/KNNTest.scala
Spark ml VectorAssembler that is often used to create input column for next pipeline components outputs sparse or dense vector for each dataset row depending which one takes less space in memory/storage.
Knn supported only dense vector as an input column type and required extra toDense transformer between assembler and knn.
This PR hopes to fix that issue by supporting also sparse vectors in input column.
@mhamilton723 please take a look.
> feat: Add sparse vector support to KNN.

- src/main/scala/com/microsoft/ml/spark/stages/PartitionConsolidator.scala
- src/test/scala/com/microsoft/ml/spark/cognitive/split1/TextAnalyticsSuite.scala
- src/test/scala/com/microsoft/ml/spark/flaky/PartitionConsolidatorSuite.scala
- move PartitionConsolidator API to stages directory
- add LocalAggregator API (to be used by LightGBM)
> feat: move partition consolidator and add LocalAggregator API

- src/main/scala/com/microsoft/ml/spark/cntk/CNTKModel.scala
Workaround for #1075 : CNTKModel does not output correct result for ResNet50 model when running on Databricks.
@mhamilton723 discovered adding a cache call works around the issue.
> fix: [Workaround] CNTKModel does not output correct result

- build.sbt
- src/main/scala/com/microsoft/ml/spark/cognitive/CognitiveServiceBase.scala
- src/main/scala/com/microsoft/ml/spark/cognitive/TextAnalyticsSDK.scala
- src/main/scala/com/microsoft/ml/spark/core/contracts/Params.scala
- src/main/scala/com/microsoft/ml/spark/io/http/SimpleHTTPTransformer.scala
- src/test/scala/com/microsoft/ml/spark/cognitive/split1/TextAnalyticsSDKSuite.scala
A small weekend experiment to try and make things a little bit clearer for the project.
This commit includes a very rough sketch base class and a sub-class implementation for language detection. 
One thing I noticed is that the Java SDK data classes are mostly _not_ ```@Serializable``` which makes it impossible ATM to reuse as-is. I've asked the SDK team to consider adding this in the next SDK version. In the meantime, we'll just need to create mirror scala case classes.
This is mostly an example as things are pretty rough. For example, most classes are in a single file, missing a bunch of schema validation, and I only included the most basic test.
> feat: TextAnalytics SDK connector POC - with language detection

- src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/PartitionProcessor.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/dataset/DatasetUtils.scala
- src/main/scala/com/microsoft/ml/spark/lightgbm/params/TrainParams.scala
- src/test/scala/com/microsoft/ml/spark/lightgbm/split2/VerifyLightGBMRanker.scala
This is in preparation for PR https://github.com/Azure/mmlspark/pull/1066.
This PR refactors the dataset-related code into the new dataset utils file and the training-related code into the partition processor.
> feat: refactor to have separate dataset utils and partition processor

- core/src/main/scala/com/microsoft/ml/spark/explainers/ImageLIME.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/ImageSHAP.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/KernelSHAPBase.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/LIMEBase.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/LocalExplainer.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/SharedParams.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/TabularLIME.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/TabularSHAP.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/TextLIME.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/TextSHAP.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/VectorLIME.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/VectorSHAP.scala
- core/src/test/scala/com/microsoft/ml/spark/explainers/split1/HasExplainTargetSuite.scala
Cause: currently, the column that contains the target classes is computed from the model transform step, but instead it should be carried from the original dataframe to be explained (before createSamples step).
> fix: explainer bug when targetClassesCol is set.

- core/src/main/scala/com/microsoft/ml/spark/explainers/LIMEBase.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/Sampler.scala
- core/src/main/scala/com/microsoft/ml/spark/explainers/TabularLIME.scala
For categorical variables, if the LIME tabular sampler created samples that do not equal the original value for all simulated samples, we end up with an all zero variable, causing NaN weights. The fix is to simply append the original row as an identity sample to the simulated samples, making sure we don't end up with an all zero variable.
> fix: LIME sometimes return NaN weights

- build.sbt
- core/src/main/scala/com/microsoft/ml/spark/automl/TuneHyperparameters.scala
Azure Synapse updated Guava to version 28.0
MoreExecutors.sameExecutorService() are not supported since Guava version >= 18
we should use this method: MoreExecutors.newDirectExecutorService()
but databricks use Guava version < 18, which don't contains MoreExecutors.newDirectExecutorService().
Therefore, I used reflection to load class "MoreExecutor" and try to get the correct Method in different environment with different Guava version.
> fix: fix Guava version issue in Azure Synapse and Databricks

- core/src/main/scala/com/microsoft/ml/spark/explainers/LassoRegression.scala
- core/src/test/scala/com/microsoft/ml/spark/core/test/base/TestBase.scala
- core/src/test/scala/com/microsoft/ml/spark/explainers/split1/LassoRegressionSuite.scala
fix: LIME returns NaN weight if a feature contains a single value or when the sampler cannot obtain a different state for a feature due to data skew. It returns zero weights for all other features.
> fix: LIME returns NaN weight if a feature contains a single value

- cognitive/src/main/scala/com/microsoft/ml/spark/cognitive/SpeechToTextSDK.scala
Error:
SpeechToText didn't support endpoint like: https://wenqxcogserv.cognitiveservices.azure.com/
It only support https://{location}.api,cognitive.microsoft.com/ like: https://eastus.api.cognitive.microsoft.com/
Also, SpeechToText don't support DEP Vnet, therefore, we don't need to consider the PE problems.
> Fix SpeechToTextSDK setLinedService Error

- cognitive/src/main/scala/com/microsoft/ml/spark/cognitive/ComputerVision.scala
- cognitive/src/test/scala/com/microsoft/ml/spark/cognitive/split1/ComputerVisionSuite.scala
To avoid possible name duplicates with .NET MLReadable functions, rename Read class to ReadImage class.
> refactor: Rename Read to ReadImage

- tools/helm/spark/Dockerfile
- tools/helm/spark/mini.Dockerfile
Security upgrade required for openjdk from 8-alpine to 17-ea-22-jdk-oracle
> Security upgrade required for openjdk from 8-alpine to 17-ea-22-jdk-oracle

- notebooks/Interpretability - Explanation Dashboard.ipynb
Using this PR and creating a new notebook instead of updating an existing notebook: https://github.com/microsoft/SynapseML/pull/1228
Closing the other PR based on comments.
======== Description from previous PR:
This PR integrates the RAI widgets with the SHAP interpretability notebook.
Specifically, it demonstrates how to create an [interpret-community style explanation](https://github.com/interpretml/interpret-community) from the local importance values, which can then be visualized in the ExplanationDashboard widget locally and optionally uploaded to AzureML.
In a near-term future TODO, the ExplanationAdapter can be integrated directly into the SHAP explainer with explain_local and explain_global APIs, so the explainer can output the explanation directly.
Please add this image in the …
> docs: add explanation dashboard integration example notebook

- notebooks/Interpretability - Explanation Dashboard.ipynb
- notebooks/Interpretability - Tabular SHAP explainer.ipynb
In the notebook, the background data should be broadcasted. When the `explain_instances` dataframe (observations to be explained) is in a mid range (50 to 100-ish), Spark will use a unexpected type of join plan, and messes up with the parallelization of the Kernel SHAP sampler, thus creating a performance bottleneck. Broadcasting the background dataset makes Spark respect the partitioning of the `explain_instances` dataframe.
These two notebooks both explain only 5 data points, so the performance bottleneck is not obvious. However, if we change 5 to 50, it becomes obvious. But if we further change it 500, Spark uses the intended join plan, and the bottleneck is not triggered.
I thought about forcing the broadcast inside the explainer, but this may create unexpected effect for other …
> fix: performance issue in interpretability notebooks

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMBase.scala
fix performance issue when comparing lightgbm to MPI by adding missing min_data_in_leaf parameter to the set of dataset params used during dataset creation
> fix: min_data_in_leaf missing from dataset parameters in lightgbm

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala
Adds `TEXT_API_LOCATION` environment variable (defaults to `eastus`) to allow overriding the Cognitive Services, alongside the existing `TEXT_API_KEY`.
> Add config to Text Api location

- website/docs/getting_started/installation.md
- website/versioned_docs/version-0.9.4/getting_started/installation.md
These changes should fix a couple of broken links on this page of website:
https://microsoft.github.io/SynapseML/docs/next/getting_started/installation/
> fix: Fix a couple of broken links

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMBase.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMClassifier.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRanker.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRegressor.scala
In benchmarking, it was discovered that lightgbm training time could be reduced 4X-10X by setting the num_threads to be equal to the # of machine cores - 1 for the single dataset mode (which is now the default mode).
This actually was already suggested in the lightgbm docs:
https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_threads
>>> for distributed learning, do not use all CPU cores because this will cause poor performance for the network communication
Poor network communication can lead to very slow training execution time.
On one scenario with a 37 GB dataset on disk with parameters:
```learning_rate = 0.1, num_leaves = 768, num_trees = 1000, min_data_in_leaf = 15000, max_bin = 512```
the training time without setting num_threads was 5.5 hours, while setting num_threads to …
> perf: improve lightgbm training performance 4x-10x by setting num_threads to be cores-1 by default for single dataset mode

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/params/TrainParams.scala
Currently there will be no objective param if a fobj is provided. 
That caused the LightGBM mistakenly think it's regression during [initial setup](https://github.com/microsoft/LightGBM/blob/master/src/io/config.cpp#L80) as that's the [default value] for it(https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/config.h#L139).
It may seem harmless at first glance as we are providing grad and hess during iteration. But it actually makes the output incorrect by having the `is_constant_hessian` to [true](https://github.com/microsoft/LightGBM/blob/master/src/boosting/gbdt.h#L402) all the time (which is the case for [unweighted regression](https://github.com/microsoft/LightGBM/blob/master/src/objective/regression_objective.hpp#L167)), and cause the calculated sum_hessian split …
> fix: correct the objective param when using fobj

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/ComputerVision.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalytics.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala
This PR contains the output from various rounds of performance testing with `TextAnalyze`
- fix #1307  - add `$top=25` to polling location to force a full maximum batch size of results from the polling endpoint
- fix handling of result data to tolerate incomplete results and add `partiallycompleted` as a terminal state to process
- add `setSuppressMaxRetriesExceededException` to allow consumers to get an error in the error column when a request reaches the maximum polling limit if they prefer that to failing a Spark task
- add `setInitialPollingDelay` option to allow a delay before the initial polling request for async API. When it is known that a request can take a certain time, this allows fine-tuning to reduce the number of requests being made
> Various improvements for TextAnalyze

- core/src/main/scala/com/microsoft/azure/synapse/ml/core/env/NativeLoader.java
This pr is recreated. origin pr is https://github.com/microsoft/SynapseML/pull/945
---
When predicting with a lightgbm model, there are so many lightgbm's so files on runtime.
It made failure on allocating memory on tmpfs in my application.
So, I tried to use java.library.path that has already "so" files.
When trying this approach, I found that it is possible to create so many /tmp/mml-nativesXXXX directories. Though, copied "so" files were not used.
Therefore, this pr is created to create lazily tempdir in NativeLoader to using getOrCreateTempDir() instead of making it in class's initializer.
> fix: lazily creating a tempdir in NativeLoader

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRanker.scala
#1336 fix repartition bug in LightGBMRanker
> fix: repartition bug in LightGBMRanker

- README.md
Update the Azure Synapse readme doc based on issue #1370, since Azure Synapse currently is on spark 3.1 and does not support 0.9.5 yet.
> docs: update the Azure Synapse readme doc

- .github/workflows/ado-pr-to-workitem.yml
This new Action will create Tasks in the destionation AzDO for every PR that is submitted to this repository.
> chore: Adding Action to sync GitHub PRs to WIs

- .github/workflows/ado-pr-to-workitem.yml
Adding back the PR -> Work Item integration, now with `pull_request_target`
> Adding ado-pr-to-workitem

- .github/workflows/ado-integration.yml
- .github/workflows/ado-pr-to-workitem.yml
Some internal AzDO information might be sensitive, so I turned them into secrets.
This also makes things easier if any of these change in the future.
> Turning sensitive AzDO data into secret

- .github/workflows/ci-test-synapsee2e.yml
- .github/workflows/ci-tests-databrickse2e.yml
- .github/workflows/ci-tests-python.yml
- .github/workflows/ci-tests-r.yml
- .github/workflows/ci-tests-unit.yml
- .github/workflows/ci-tests-websitesamples.yml
CI/Tests/Unit were not running tests. The reason was that we were referencing the Environment Variable `PACKAGE` as `$(PACKAGE)`, and in GitHub Workflows it needs to be `${PACKAGE}`.
I've also fixed the fact that newer Test Results were always overwriting older ones. To do that, I gave each test run a unique name.
> fix: Unit Tests not executing in WF; Test Results overwritten

- notebooks/features/responsible_ai/Interpretability - Explanation Dashboard.ipynb
Fix breaking ADB test because itsdangerous package has a latest update that remove the deprecated usage of importing json directly.
> fix: fix breaking ADB test

- website/src/pages/index.js
Update website homepage installation guidance's Spark3.1 version of SynapseML, we use version 0.9.5-13-d1b51517-SNAPSHOT for now that includes latest features.
Tested UI rendering.
> fix: update website doc of Spark3.1 version installation on Synapase

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/AnomalyDetection.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/AnomalyDetectorSchemas.scala
This PR upgrades the version of the univariate anomaly detection API endpoint to `v1.1-preview.1` to add support for an optional parameter `imputeMode` in the input, and expect severity scores in the output.
> feat: Upgrade the univariate anomaly detection version to v1.1-preview

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMBase.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMClassifier.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRanker.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRegressor.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMUtils.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/TrainUtils.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/dataset/DatasetAggregator.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/dataset/DatasetUtils.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/params/LightGBMParams.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/params/TrainParams.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/swig/SwigUtils.scala
- lightgbm/src/test/scala/com/microsoft/azure/synapse/ml/lightgbm/split1/VerifyLightGBMClassifier.scala
- add random seed parameters to lightgbm
- start to debug github issues:
https://github.com/microsoft/SynapseML/issues/1332
https://github.com/microsoft/SynapseML/issues/928
https://github.com/microsoft/SynapseML/issues/997
https://github.com/microsoft/SynapseML/issues/564
> fix: add seed parameters to lightgbm

- core/src/main/scala/com/microsoft/azure/synapse/ml/core/utils/JarLoadingUtils.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/swig/SwigUtils.scala
Some tests rely on the ability to reflect all classes in the synpaseml package (e.g. to filter to a set of all classes derived from a particular parent class).  The current implementation uses ClassPath.from() from a spark utility package.  However, this utility only works for ClassLoaders derived from UrlClassLoader (not well documented limitation).  In the context of sbt, this is true, so things work in pipelines and such. In IntelliJ, the ClassLoaders are the standard App/Ext/Boot trio, which are not, so any test using this pathway fails since ClassPath.from() returns an empty list.  
This PR adds a double check so that if the reflected class list from ClassPath comes back empty, it falls back to a manual lookup. This lookup is slower, so the choice was to not replace it, but instead …
> fix: Fix reflective class loading in IntelliJ

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMBase.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/SharedState.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/TaskTrainingMethods.scala
Lightgbm can get stuck when SingleDatasetMode is enabled and if an empty partition is, by random chance, chosen as the main worker in the executor.
The fix is to only allow non-empty partitions to be chosen as the main worker.
Run the test "Verify LightGBM Classifier won't get stuck on empty partitions" in the file:
https://github.com/microsoft/SynapseML/blob/master/lightgbm/src/test/scala/com/microsoft/azure/synapse/ml/lightgbm/split1/VerifyLightGBMClassifier.scala#L610
many times, by random chance it will often get stuck after several runs.
No dependency changes.
> fix: lightgbm getting stuck when empty partition is chosen as the main worker in singleDatasetMode

- core/src/main/scala/com/microsoft/azure/synapse/ml/core/utils/ParamsStringBuilder.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/core/utils/VerifyParamsStringBuilder.scala
- pipeline.yaml
- vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitBase.scala
With the recent parameter refactoring, all Array[T] parameters were converted to build as comma-separated lists (e.g. {"aa", "bb"} => "q=aa,bb").  For Vowpal Wabbit parameter "q", this is a regression.  The parameter should be repeated once for each array element, e.g. "q=aa q=bb".  I added a new appendRepeatableParamIfNotThere method to the ParamsStringBuilder that can handle this special case.
Extended existing ParamsStringBuilder tests to include the new appending methods.
> fix: Fix building of quadratic parameter in Vowpal Wabbit

- core/src/main/python/synapse/ml/automl/HyperparamBuilder.py
- core/src/main/scala/com/microsoft/azure/synapse/ml/automl/HyperparamBuilder.scala
GridSpace python API not working:
```python
searchSpace = paramBuilder.build()
gridspace = GridSpace(searchSpace)
```
```
py4j.protocol.Py4JError: An error occurred while calling None.com.microsoft.azure.synapse.ml.automl.GridSpace. Trace:
py4j.Py4JException: Constructor com.microsoft.azure.synapse.ml.automl.GridSpace([class [Lscala.Tuple2;]) does not exist
at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:179)
at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:196)
at py4j.Gateway.invoke(Gateway.java:237)
at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
at py4j.GatewayConnection.run(GatewayConnection.java:238)
at …
```
> fix: GridSpace python API not working

- pipeline.yaml
There are two tasks for build-ing and push-ing minimal Docker Image. They both are incorrectly named the same as "Minimal Image Build + Push" -- fixing the confusion here.
N/A
None.
N/A
> fix: task displayName for minimal Dockerfile

- pipeline.yaml
This change adds building and pushing Developer Docker Image alongside demo and the minimal docker image as part of validation checks
None
Not Applicable
AB#1750634
> fix: Build Developer Docker Image in Pipeline Tasks

- .gitignore
Fixes relative path where notebook test files (*.py & *.txt) that are generated as a part of code compilation that should be ignored by git as these are runtime generated files that should not be checked in. 
Made sure that with the changes, even after running `sbt setup` the notebook/**/*.py files don't show up on `git status` as untracked files that confuses the end user.
`sbt setup && git status` WITHOUT these changes:
```
git status
On branch foobar
Your branch is up to date with 'origin/master'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   .gitignore
Untracked files:
(use "git add <file>..." to include in what will be committed) …
```
> chore: Fix path for notebook test files in gitignore

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMBase.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMUtils.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/dataset/DatasetAggregator.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/swig/SwigUtils.scala
- lightgbm/src/test/scala/com/microsoft/azure/synapse/ml/lightgbm/split1/VerifyLightGBMClassifier.scala
This PR fixes the chunksize being incorrectly specified during data copy in single dataset mode.  This PR should resolve the user issue: https://github.com/microsoft/SynapseML/issues/1478
Specifically, the chunk size for the features array was actually specified to be ```num_cols * default_chunksize```, hence using just the default chunksize is incorrect during the data copy operation.  The PR uses the chunksize retrieved from the array directly.
Also, this PR removes the unused method ```getNumRowsForChunksArray```.
A test was added to validate that specifying different chunk size values should not have any impact on the model metrics.  The chunk size is only for copying data and should not have any impact on the model's accuracy.
There are no dependency changes in this PR.
AB#1761413
> fix: chunksize parameter incorrectly specified during data copy

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/FormOntologyLearner.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/FormRecognizer.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/FormRecognizerV3.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/FormRecognizerV3Schemas.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/FormOntologyLearnerSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/FormRecognizerSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/FormRecognizerV3Suite.scala
> fix: fix issues with form recognizer parsing and form ontology learner

- lightgbm/src/main/python/synapse/ml/lightgbm/mixin.py
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMClassifier.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMModelMethods.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRanker.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMRegressor.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/booster/LightGBMBooster.scala
- lightgbm/src/test/scala/com/microsoft/azure/synapse/ml/lightgbm/split1/VerifyLightGBMClassifier.scala
This PR adds the ability to get the native lightgbm model directly as a string.
This is for the spark version of error analysis, to retrieve the trained surrogate model on errors for traversal in the RAI toolbox:
https://github.com/microsoft/responsible-ai-toolbox/blob/main/erroranalysis/erroranalysis/_internal/surrogate_error_tree.py#L296
For more information on error analysis please see:
https://github.com/microsoft/responsible-ai-toolbox/blob/main/docs/erroranalysis-dashboard-README.md
I validated that I can get the model string from the LightGBM model.
No dependency changes required.
AB#1800563
> feat: Add method to get lightgbm native model string directly

- core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala
Fix breaking onnx notebook in databricks e2e test. onnxmltools released a new version and the dependency on onnxruntime contains errors.
Ran dbx tests.
None.
AB#1826714
> fix: fix databricks test

- hooks/pre-commit
Add sbt scalastyle check for both main/test projects so that we won't forget fix them until seeing the pipeline fails.
Local tested
None.
AB#1828400
> style: add scalastyle check into hooks

- pipeline.yaml
Style check currently fails without any verbosity on what line(s) need fixing. The developer will have no idea on what line(s) to fix unless he/she runs the black tool locally. Given we can show this on our checks in the pipeline, that would be useful for the developer.
With verbosity: [ADO Pipeline link](https://msdata.visualstudio.com/A365/_build/results?buildId=65190468&view=logs&jobId=3f85e25b-fb23-5eb7-8385-51966a33df73&j=3f85e25b-fb23-5eb7-8385-51966a33df73&t=7a397729-aae9-5f53-8015-ab5fa5af6899)
Without verbosity: [ADO Pipeline link](https://msdata.visualstudio.com/A365/_build/results?buildId=65185618&view=logs&jobId=3f85e25b-fb23-5eb7-8385-51966a33df73&j=3f85e25b-fb23-5eb7-8385-51966a33df73&t=7a397729-aae9-5f53-8015-ab5fa5af6899)
None
AB#1832624
> fix: make style check verbose

- .pre-commit-config.yaml
- requirements.txt
Adds `pre-commit` configuration for general linting / formatting of python & markdown files. Once we install pre-commit locally, this check would
- check for any code style issues, AND
- fix them
before a `git commit` completes
For more information, please read: [pre-commit docs](https://pre-commit.com/)
THIS DOES NOT FORMAT / CHECK SCALA CODE
None
pre-commit python package
AB#1834318
> feat: add pre-commit support

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/dataset/DatasetAggregator.scala
- lightgbm/src/test/scala/com/microsoft/azure/synapse/ml/lightgbm/split1/VerifyLightGBMClassifier.scala
In a recent PR to fix multi-class initial scores (https://github.com/microsoft/SynapseML/pull/1526), a bug was introduced that broke single-class initial scores for useSingleDatasetMode == true.  The bug is non-deterministic from the standpoint of model improvement, so it was not detected by the existing tests (fails only sporadically).
Basically, in the previous PR, a method was extracted that used the non-useSingleDataset mode way of adding initial data, but coalesceTo cannot be used to insert in the middle of an array at a startIndex.  The fix was to simply use the appropriate way to insert scores for a shared dataset.
Added coverage for both useSingleDatasetMode == true and useSingleDatasetMode == false to existing test.
N/A
AB#1867252
> fix: Fix useSingleDataset mode single class initial scores

- .github/workflows/label-add-triage.yml
Adds a Github workflow to label new/reopened issues with `triage` label. This will help maintainers to know what issues need attention.
Workflow will need to be tested once we have this merged to main branch.
None.
AB#1889230
> chore: Add GH workflow to label new/reopened issues

- README.md
- website/docs/getting_started/installation.md
- website/src/pages/index.js
- website/versioned_docs/version-0.10.0/getting_started/installation.md
Per testing on Synapse spark3.2 pool, we need to exclude com.fasterxml.jackson.core:jackson-databind package in order to successfully start the spark session.
not needed.
None.
AB#1890257
> docs: update installation guidance of v0.10.0

- .github/workflows/acknowledge-new-issues.yml
- .github/workflows/acknowledge-new-prs.yml
None
Editing the welcome message posted on new PRs/Issues
Used markdown to preview the text
AB#1893152
> chore: Format welcome message with emojis

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/FormRecognizerV3Suite.scala
> fix: fix flaky forms test

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/ComputerVision.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/ComputerVisionSuite.scala
Allows one to use AnalyzeImage in a privacy compliant way
> feat: Add the `descriptionExcludes` parameter to `AnalyzeImage`

- opencv/src/main/python/synapse/ml/opencv/ImageTransformer.py
Changed `toNDArray` method to also support converting gray scale images to numpy arrays for further transformations on those arrays.
AB#1909273
> feat: Support gray scale images in `toNDArray`

- .github/stale.yml
None
Add [Stale](https://github.com/apps/stale) robot for automatically marking issues as stale after 60 days (the number can vary)
not applicable
AB#1915196
> feat: add stale bot for issues

- notebooks/community/aisamples/AIsample - Time Series Forecasting.ipynb
- website/notebookconvert.py
None
Add time series forecasting notebook for aisample under notebooks/community/aisample.
AB#1928947
> docs: add aisample time series forecasting

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/OpenAISuite.scala
- notebooks/features/cognitive_services/CognitiveServices - OpenAI.ipynb
> chore: update openai service to official deployment, and disable test due to outage

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/CognitiveServiceBase.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/DocumentTranslator.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/SpeechToText.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextTranslator.scala
No issues. There was a related IcM ticket.
For gov regions the cog service endpoint is different.
AB#1937420
> fix: fix translator endpoint and update all endpoints for gov regions

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split2/SpeechToTextSuite.scala
None
Fix failing SpeechToText suite.
AB#1940836
> fix: fix speechToTextSuite serializationFuzzing failure

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalytics.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/TextAnalyticsSDK.scala
> chore: deprecate old Text analytics APIs to prepare for refactor

- build.sbt
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/ComputerVision.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/MultivariateAnomalyDetection.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/SlimStorageClient.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/AnamolyDetectionSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split4/MultivariateAnamolyDetectionSuite.scala
- notebooks/features/cognitive_services/CognitiveServices - Multivariate Anomaly Detection.ipynb
- website/docs/documentation/estimators/cognitive/_MAD.md
> chore: Remove MVAD's dependence on hardwired credentials and azure SDKs

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/ComputerVision.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/MultivariateAnomalyDetection.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/ComputerVisionSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split4/MultivariateAnamolyDetectionSuite.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/codegen/DefaultParamInfo.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/codegen/Wrappable.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/featurize/text/PageSplitter.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/recommendation/RankingAdapter.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/stages/StratifiedRepartition.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/core/test/fuzzing/Fuzzing.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/recommendation/RankingAdapterSpec.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/recommendation/SARSpec.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/stages/TextPreprocessorSuite.scala
- deep-learning/src/main/scala/com/microsoft/azure/synapse/ml/onnx/ONNXModel.scala
- deep-learning/src/test/scala/com/microsoft/azure/synapse/ml/onnx/ONNXModelSuite.scala
- pipeline.yaml
- src/test/scala/com/microsoft/azure/synapse/ml/core/test/fuzzing/FuzzingTest.scala
- vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitInteractions.scala
> chore: improve test coverage

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TranslatorSuite.scala
> fix: fix flaky translate tests

- notebooks/community/aisamples/AIsample - Time Series Forecasting.ipynb
None
Add MLFlow logging and loading to Time Series Forecasting sample notebook
AB#1966880
> docs: add MLFlow in ai sample time series forecasting

- core/src/main/scala/com/microsoft/azure/synapse/ml/explainers/SharedParams.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/explainers/split1/HasExplainTargetSuite.scala
NA
KernelSHAP throws error when the key in the ZipMap output of an ONNX model is of LongType. Adding more type checks to make sure all IntegralTypes can be supported as key type. IntegralType itself is private so I cannot use that type itself.
5. Don't forget to add `` before each python code blocks to enable auto-tests …
> fix: KernelSHAP throws error when the key type in the ZipMap output is LongType

- deep-learning/src/main/scala/com/microsoft/azure/synapse/ml/onnx/ONNXHub.scala
- deep-learning/src/test/scala/com/microsoft/azure/synapse/ml/onnx/ONNXModelSuite.scala
#xxx
Improve ONNX Hub test reliability
> test: Improve ONNXtests reliability

- core/src/test/scala/com/microsoft/azure/synapse/ml/Secrets.scala
- src/test/scala/com/microsoft/azure/synapse/ml/core/test/fuzzing/FuzzingTest.scala
> chore: add secret scanning infrastructure

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/FaceSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split4/MultivariateAnamolyDetectionSuite.scala
#xxx
clarify date comparisons when deleting old models/groups
- [x ] No. You can skip this section.
- [x ] No. You can skip this section.
> fix: clarify date comparisons when deleting old models/groups

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/form/FormRecognizer.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/text/TextAnalytics.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/text/TextAnalyticsSuite.scala
> fix: fix modelVersion param in TextAnalytics

- build.sbt
To remove the `enablePlugins(SbtPlugin)` in `build.sbt` for modules that are not themselves SBT plugins.
This is unnecessary and prevents cross-building to Scala 2.13, which is what I'm actually trying to get at.
By running `sbt test:compile` and checking that compilation still works (it wouldn't if one of the modules was actually an SbtPlugin).
> build: Remove unnecessary SbtPlugin settings

- core/src/main/scala/com/microsoft/azure/synapse/ml/causal/DoubleMLEstimator.scala
fix namespace import for Experimental, from jdk.jfr.Experimental to org.apache.spark.annotation.Experimental
> fix: namespace import for Experimental

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/speech/SpeechSchemas.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/speech/SpeechToTextSDK.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/speech/SpeechToTextSDKSuite.scala
- notebooks/features/cognitive_services/CognitiveServices - Create a Multilingual Search Engine from Forms.ipynb
> feat: word level timing information for Speech to Text

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAI.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAISuite.scala
> feat: add aad auth for openAI

- website/versioned_docs/version-0.9.5/features/responsible_ai/Interpretability - Explanation Dashboard.md
#1555 
changed of `model.transform` to `self.model.transform`
> docs: fixed typo in Update Interpretability - Explanation Dashboard.md 

- build.sbt
Upgrading the Onnx version which has the shaded classes in a regular jar and avoids the classifier need.
Tested using Databricks spark3.3 cluster
> fix: Upgrading Onnx-protobuf version to overcome the assembly usage

- notebooks/features/regression/Regression - Vowpal Wabbit vs. LightGBM vs. Linear Regressor.ipynb
Update learning rate. @jackgerrits I assume that the defaults maybe changed? Learning rate was 7 and I changed to 0.5 (did a small hyper parameter search). 
Compared RMSE
> fix: VW adjust learning rate for boston data example

- core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala
- notebooks/features/cognitive_services/CognitiveServices - Create Audiobooks.ipynb
> docs: Add audiobook generation example

- core/src/test/scala/com/microsoft/azure/synapse/ml/causal/VerifyDoubleMLEstimator.scala
Based on mock dataset. The ATE can't be lower than -130 or greater than 130, and the estimate could be 0.0.
> fix: Update DoubleMLEstimator test CI verification

- pipeline.yaml
Adding CONTRIBUTORS.md and SECURITY.md to the path exclusion list
> build: Exclude contributors and security markdown docs from build triggers

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/CognitiveServiceBase.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/form/FormRecognizerV3.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/language/AnalyzeText.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAI.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAIChatCompletion.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAICompletion.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAIEmbedding.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAIPrompt.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAISchemas.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAIChatCompletionSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAICompletionSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAIEmbeddingsSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/openai/OpenAIPromptSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/translate/TranslatorSuite.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/causal/VerifyDoubleMLEstimator.scala
- notebooks/features/cognitive_services/CognitiveServices - OpenAI.ipynb
> feat: Add ChatGPT through the `OpenAIChatCompletion` transformer

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/search/SearchWriterSuite.scala
#xxx
Clean up old and/or missed search indexes in SearchWriterSuite
> fix: clean up old/missed search indexes in SearchWriterSuite

- .gitignore
.bloop is used by metals in VS code
#xxx
> chore: add .bloop to .gitignore

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/cognitive/speech/SpeechAPI.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/language/AnalyzeTextSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/speech/SpeechToTextSDKSuite.scala
- core/src/test/python/synapsemltest/cyber/anamoly/test_collaborative_filtering.py
- environment.yml
- pipeline.yaml
> fix: fix language tests

- core/src/main/scala/com/microsoft/azure/synapse/ml/causal/DoubleMLEstimator.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/causal/ResidualTransformer.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/train/AutoTrainer.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/train/TrainClassifier.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/train/TrainRegressor.scala
When applying DML on WExp project, the data has >1M records and >5 categorical features, DML run got timeout even with a large cluster.
We figured out that it's due to Synapse version of Spark optimizer won't be able to handle a complex query plan, split DML pipeline and cache each pipeline result, can fix the timeout issue.
with internal project data
> fix: DML run get timeout if big dataset has more feature columns (Workaround Synapse Spark optimizer issue)

- website/docs/features/causal_inference/about.md
#xxx
Update causal inference docs: discrete treatment column data type must be int or bool.
- [x ] No. You can skip this section.
- [x ] No. You can skip this section.
6. Make sure the `WebsiteSamplesTests` job pass in the …
> docs: note discrete treatment data type

- deep-learning/src/main/scala/com/microsoft/azure/synapse/ml/onnx/ONNXUtils.scala
- deep-learning/src/test/scala/com/microsoft/azure/synapse/ml/onnx/ONNXModelSuite.scala
#1902 
Add support in ONNX model shape inference when the input batch has shape [-1].
> fix: ONNX model shape inference cannot handle batch with shape [-1]

- website/docs/getting_started/installation.md
Make installation instruction in the webpage consistent with the README file in the section related to `sbt`: <https://github.com/microsoft/SynapseML/blob/master/README.md#sbt>.
There may be other parts in the <https://github.com/microsoft/SynapseML/blob/master/README.md> that are not updated in <https://microsoft.github.io/SynapseML/docs/getting_started/installation/>, but I didn't check anything else.
> docs: Fix installation instruction in the webpage for the `build.sbt` file

- core/src/main/scala/com/microsoft/azure/synapse/ml/automl/FindBestModel.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/automl/VerifyFindBestModel.scala
#1987
Uses the correct ordering when selecting the best metric.
> fix: bug #1987 ordering in FindBestModel

- website/src/pages/index.js
> docs: update website synapse info and fabric installation

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/NetworkManager.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/StreamingPartitionTask.scala
Fix a bug in exception handling and improve logs for LightGBM
> fix: Improve LGBM exception and logging

- tools/docgen/README.md
- tools/docgen/docgen/__main__.py
- tools/docgen/docgen/channels.py
- tools/docgen/setup.py
add missing package dependency
fix channel resolution
#xxx
> fix: improve docgen

- core/src/test/scala/com/microsoft/azure/synapse/ml/Secrets.scala
- src/test/scala/com/microsoft/azure/synapse/ml/core/test/fuzzing/FuzzingTest.scala
> chore: remove secret scanner

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/BasePartitionTask.scala
- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/StreamingPartitionTask.scala
If a zero-count partition gets assigned to create the validation Dataset, it fails. The fix is simply to not let this scenario happen.
> fix: Fix problem with empty partition assigned to validation data

- .github/workflows/on-pull-request-target-review.yml
Verified that 0.9.4 has a dependency issues and reached out to owner who kindly cut a new release
> fix: updated gpt-review to version 0.9.5 to fix break

- docs/Explore Algorithms/Vowpal Wabbit/Quickstart - Classification using VW-native Format.ipynb
- website/docusaurus.config.js
- website/package.json
- website/src/theme/NotFound/index.js
- website/yarn.lock
> chore: turn off barrier exec mode in VW generic sample

- pipeline.yaml
- project/Secrets.scala
- tools/esrp/prepare_jar.py
> Esrp release

- core/src/main/scala/com/microsoft/azure/synapse/ml/fabric/TokenLibrary.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/logging/fabric/CertifiedEventClient.scala
Factor accesstoken wrapper into a separate class so it can be consumed by others as well.
Certified event tests
> feat: factor accesstoken runtime-dependency wrapper out

- lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/NetworkManager.scala
Just some better log/excpetion handling for network issues to give more diagnostic information
> refactor: Improve LightGBM Network logs

- tools/pypi/generate-pypi-mfa-qr.py
PyPi is now requiring MFA. I set up the necessary MFA configuration in PyPi and have stored relevant credentials in our secret store.
For convenience I'm providing this script to generate an MFA QR code for team PyPi maintainers.
e.g. (not a real QR code)
> chore: Add script to generate pypi mfa qr

- build.sbt
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/CognitiveServiceBase.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAI.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIChatCompletion.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAICompletion.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIEmbedding.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/text/TextAnalytics.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/translate/TextTranslator.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/fabric/FabricClient.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/fabric/FabricTokenParser.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/fabric/OpenAITokenLibrary.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/fabric/RESTUtils.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/fabric/TokenLibrary.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/logging/common/PlatformDetails.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/logging/fabric/CertifiedEventClient.scala
Support token provider auth mode, auto refresh token while job is running.
- [] Yes. Make sure the dependencies are resolved correctly, and list changes here.
> chore: Support Token Provider Mode

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/speech/SpeakerEmotionInferenceSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/speech/SpeechToTextSDKSuite.scala
> chore: rotate outdates SAS url in speech tests

- pipeline.yaml
Excluding documents that shouldn't be tested from triggering test builds
> chore: exclude non-executable docs from automated tests

- core/src/main/scala/com/microsoft/azure/synapse/ml/codegen/Wrappable.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/core/utils/JarLoadingUtils.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/codegen/TestRegressor.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/codegen/WrappableTests.scala
- src/test/scala/com/microsoft/azure/synapse/ml/core/test/fuzzing/FuzzingTest.scala
This commit addresses an issue in the companionModelClassName method where the resolution of the companion model's class name was not accurately reflecting the intended Python package path for Regression models.
"from M import M", where M is the name of MLLib's `Regressor` class' concrete model type parameter:
https://github.com/apache/spark/blob/45ba9224602eb18fe45e339cbb8cf2e8a4924f0b/mllib/src/main/scala/org/apache/spark/ml/regression/Regressor.scala#L28
Implemented reflection with scala.reflect.runtime.universe._ to accurately access and utilize type information at runtime, overcoming Scala's type erasure limitations.
Tested against the existing method for all wrappable classes and found the only divergence to be the instance where it fixed the broken wrapped regressor. Added a …
> fix: companionModelClassName no longer returns generic type variable

- templates/conda.yml
> chore: add conda env caching

- pipeline.yaml
> chore: break up build steps to improve stability

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/search/SearchWriterSuite.scala
- pipeline.yaml
- templates/update_cli.yml
> chore: remove hack for materializing keys

- .github/workflows/check-semantic-prs.yaml
n/a
Checking the PR title in the workflow is done with the specific github action `amannn/action-semantic-pull-request@v5.4.0`.
It's recommended to set the permission to `permissions: pull-request: read` based on the actions docs [here](https://github.com/amannn/action-semantic-pull-request?tab=readme-ov-file#installation).
n/a
> ci: set pull-requests read permission

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAI.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIEmbedding.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAICompletionSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIEmbeddingsSuite.scala
- website/versioned_docs/version-1.0.4/Explore Algorithms/OpenAI/OpenAI.md
Closes #2177 
Adding support for `dimensions` parameter when calling OpenAI Embeddings endpoint to reduce the size of the embedding vecor.
Added `Extra Param Usage` test to OpenAIEmbeddingSuite
Added example to existing OpenAI.md
5. Don't forget to add `` before each python code blocks to enable auto-tests for python …
> chore: add support for dimensions parameter to OpenAIEmbedding

- core/src/main/scala/com/microsoft/azure/synapse/ml/logging/common/PlatformDetails.scala
Based on Internal Bug Reports
Fix wrong platform detection result when the utility function is first run in a thread with no spark context access.
> fix: Fix Platform Detection Logic on Fabric

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/form/FormRecognizerV3.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/form/FormRecognizerV3Schemas.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/CognitiveServicesCommon.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/form/FormRecognizerSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/translate/TranslatorSuite.scala
- pipeline.yaml
> chore: fix errors in build pipeline

- core/src/main/scala/com/microsoft/azure/synapse/ml/logging/common/PlatformDetails.scala
- docs/Reference/Developer Setup.md
Updating the Developer Setup instructions to remove the WinUtils step (which is no longer needed), and adding a step to update the Run Configuration of ScalaTest. This update should get rid of the following bug that occurs when testing a freshly setup SynapseML:
Exception java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x7f992c3a) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x7f992c3a
Minor change updating Developer Setup 
Only a documentation change. 
2. Follow the pattern …
> docs: Update Developer Setup to remove WinUtils step and include ScalaTest Configuration update. 

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/CognitiveServiceBase.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAI.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIChatCompletionSuite.scala
Adding custom base url and headers to access additional OpenAI endpoint deployments
- Adding trait HasCustomHeader that checks if a customHeader was assigned.
- Adding customHeader to the addHeaders function to iterate through the Map of headers provided and assign them to the request.
- Added customRootUrl - if provided will be used instead of the prepareUrlRoot() function
- deploymentName parameter was changed to not required
3. Make sure the `DocTable` points to correct …
> feat: Adding Custom Url Endpoints and Headers

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/CognitiveServiceBase.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIChatCompletionSuite.scala
https://github.com/microsoft/SynapseML/pull/2232
Added support for pyspark dict input for parameter 'setCustomHeaders'
> fix: Make setCustomHeaders compatible with Pyspark

- core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/RESTHelpers.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/nbtest/DatabricksUtilities.scala
- docs/Explore Algorithms/Deep Learning/Quickstart - Fine-tune a Vision Classifier.ipynb
- pipeline.yaml
> chore: fix remaining build errors

- core/src/main/python/synapse/ml/core/logging/SynapseMLLogger.py
- core/src/test/python/synapsemltest/core/test_logging.py
#xxx
Adds feature name as a parameter to log_verb to allow us to use it when using the decorator to log.
> chore: Add feature name to log_verb

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIChatCompletion.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAICompletion.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIPrompt.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIPromptSuite.scala
#xxx
Custom headers are supported in both OpenAIChatCompletion and OpenAICompletion - but not in OpenAIPrompt. Passing functionality through to enable the same in OpenAIPrompt
6. Make sure the `WebsiteSamplesTests` job pass in …
> chore: Add HasOpenAICognitiveServiceInput to OpenAIPrompt

- core/src/main/python/synapse/ml/core/logging/SynapseMLLogger.py
#xxx
minor change to fix a KeyError bug that occurs if kwargs is defined but "df" isn't a valid key. .get("df") will return None if "df" doesn't exist, short-circuiting the conditional and avoiding the error. 
6. Make sure the …
> fix: tiny bug fix to avoid KeyError

- core/src/test/scala/com/microsoft/azure/synapse/ml/core/test/fuzzing/Fuzzing.scala
> chore: make debugging getterSetter tests easier

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/anomaly/AnomalyDetection.scala
> fix: update default anomaly detector version to compatible non-preview

- core/src/main/scala/com/microsoft/azure/synapse/ml/fabric/OpenAIFabricSetting.scala
Need to use mwc token when accessing fabric openai endpoints, AAD token will be banned and also AAD is not enough to show workspace permission
Replace AAD token with MWC token
Manual
> fix: change to use mwc token in tenant setting check

- docs/Explore Algorithms/OpenAI/Langchain.ipynb
With release of new version of NLTK (3.9.1), the unit test started failing. 
The version of NLTK is pinned to `3.8.1` in the notebook
I have manually ran the `Longchain.ipynb` and validated that it is not failing anymore.
6. …
> fix: Using nltk version 3.8.1 Azure Databricks Notebook longchain.ipynb to fix failing test

- pipeline.yaml
- templates/kv.yml
`AzureKeyVault` task version has been deprecated and needs to be updated to the latest version. `GitRelease` task has also been deprecated. By updating these two tasks, we will get fewer warnings. It will reduce warnings from over 160 to about 60.
Updating task version to 1 from 0 for `GitRelease` and `AzureKeyVault`
Pipeline change only.
> chore: Updating AzureKeyVault task version

- cognitive/src/main/python/synapse/ml/services/openai/OpenAIDefaults.py
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIDefaults.scala
- cognitive/src/test/python/synapsemltest/services/openai/test_OpenAIDefaults.py
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIDefaultsSuite.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/HTTPTransformer.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/param/GlobalParams.scala
#xxx
Wrap OpenAIDefaults to work for PySpark, and add URL as a OpenAIDefault. 
> chore: Wrap OpenAIDefaults for Python

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAI.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIChatCompletion.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIPrompt.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIChatCompletionSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAICompletionSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIPromptSuite.scala
OpenAI chat completion accepts `response_format` as request parameter. Setting this parameter as `json_object`guarantees that response from OpenAi service will be in JSON format. It does also require that one of the prompt must also have the word JSON in it. In this PR, we are adding a new field in request, which can be `json_object` or `text` as prescribed by OpenAI. In case it is set as `json_object`, then we also add a system prompt instructing openAI to respond in JSON format.
Unit tests have been added to validate this functionality
We have added new field ChatCompletion class that takes responseFormat as parameter.
Make sure you choose the correct class `estimators/transformers` and …
> chore: Adding responseFormat parameter in OpenAI Chat Completion Request

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIPrompt.scala
A couple of bug fixes:
- move error column to back
- rename error column 
- fix issue where params that don't exist were being checked
6. Make sure the …
> chore: OpenAIPrompt bug fixes

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/language/AnalyzeText.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/language/AnalyzeTextJobSchema.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/language/AnalyzeTextJobServiceTraits.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/language/AnalyzeTextLROTraits.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/language/AnalyzeTextLongRunningOperations.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/language/AnalyzeTextLROSuite.scala
- core/src/test/scala/com/microsoft/azure/synapse/ml/Secrets.scala
Adding a  new capability to use Cognitive Service Language Service asynchronously.
The transformer calls the async service and poll for result. The polling delay and max retry attempts is controlled by parameters. Request creation for each task is extracted into separate trait to make code more readable and manageable. There has been minimal changes in AnalyzeText class.
In this PR we adding support for following tasks
*  ExtractiveSummarization
*  AbstractiveSummarization
*  Healthcare
*  SentimentAnalysis
*  KeyPhraseExtraction
*  PiiEntityRecognition
*  EntityLinking
*  EntityRecognition
*  CustomEntityRecognition
*  CustomMultiLabelClassification
*  CustomSingleLabelClassification
Using unit tests, I have called each service and validated that transformer is working.
> feat: Adding capability use Cognitive Service Language Service asynchronously for Summarization

- core/src/main/scala/com/microsoft/azure/synapse/ml/fabric/FabricClient.scala
We noticed that Spark jobs didn't have `trident.artifact.workspace.id` set, rather opting for `trident.workspace.id`. So, we've added an check to get `trident.workspace.id` if `trident.artifact.workspace.id` is not set. 
6. …
> fix: Workspace ID fix for Spark Jobs

- core/src/main/scala/com/microsoft/azure/synapse/ml/io/http/HTTPClients.scala
- core/src/main/scala/com/microsoft/azure/synapse/ml/logging/SynapseMLLogging.scala
We are putting all request contents into logs, which just add unnecessary noise in the logs and we add the same message twice. I am ensuring that message is only added for debug.
Reduce log by not logging entire messages twice
Just removing logs
> chore: Removing unnecessary logs

- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIEmbeddingsSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/search/SearchWriterSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/speech/TextToSpeechSuite.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/text/TextAnalyticsSuite.scala
- environment.yml
- pipeline.yaml
There have been failng unit tests, and I am finxing these failures.
In SearchWriter suite, I am ensuring that we cleanup at the start as well. I have manually cleaned up older search indexes
In TextAnalytics suite, the return confidence is now 0.66, so I have fixed it to 0.5. We don't want to validate working of TextAnalytics service
Finally, for deep learning test, 99% of time is spent in Garbage collection, so I am removing Xmx, to let JVM decide how much it wants to consime memory.
2. Follow the pattern in markdown file and add another section for your new API, including pyspark, scala (and .NET potentially) …
> chore: Making unit tests green again

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIDefaults.scala
- cognitive/src/test/python/synapsemltest/services/openai/test_OpenAIDefaults.py
#xxx
User found a bug where URLs set without a trailing "/" don't work. Checking for the "/" and adding it now. 
> fix: Adding trailing / to URLs set

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/search/AzureSearchSchemas.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/search/SearchWriterSuite.scala
Fixes #2382
Fixes `DeserializationException` when writing data to Azure Search indices that contain scoring profiles. The JSON parser was expecting scoring profiles to be simple strings but Azure Search returns complex JSON objects.
**Changes:**
- Add proper case classes for scoring profiles (`ScoringProfile`, `ScoringFunction`, etc.) in `AzureSearchSchemas.scala`
- Update `IndexInfo.scoringProfiles` type from `Option[Seq[String]]` to `Option[Seq[ScoringProfile]]`
- Add JSON formatters for all scoring profile-related case classes in `AzureSearchProtocol`
- Support all scoring function types: freshness, magnitude, distance, and tag functions
- Add comprehensive test to verify scoring profile parsing works correctly
This allows users to write data to Azure Search indices that have scoring …
> fix: support scoring profiles in Azure Search index parsing

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIPrompt.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/openai/OpenAIPromptSuite.scala
> chore: fix failing openai tests

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/search/AzureSearch.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/search/SearchWriterSuite.scala
Fixes #2380
Fixes inconsistent behavior in Azure Search where index creation succeeded with DateType/TimestampType columns but data writing failed due to schema parity check expecting StringType.
**Changes:**
- Add automatic date/timestamp to ISO8601 conversion in `prepareDF` method
- Handle TimestampType with UTC conversion before formatting  
- Handle DateType as midnight UTC in ISO8601 format
- Update `edmTypeToSparkType` mapping: `Edm.DateTimeOffset` → `DateType` (was `StringType`)
- Add tests for date handling including null values and timezone scenarios
This eliminates the previous two-step workflow where users had to manually convert dates to strings after initial index creation.
**Tests added:**
- `test("Handle date fields correctly")` - Basic date/timestamp handling with null …
> fix: auto-convert DateType/TimestampType to ISO8601 in Azure Search

- core/src/main/scala/com/microsoft/azure/synapse/ml/fabric/FabricClient.scala
N/A
When workspace pl is enabled, FQDNs are different
Manual
> feat: Support Choosing Fabric WSPL FQDN

- templates/codecov.yml
Codecov bash uploader has been deprecated and causing intermittent pipeline failures. As per Codecov recommendation we are moving to use the cli to upload.
Updated pipeline step to run codecov cli.
Merge validation pipeline would run without error
> chore: Updating codecov pipeline step

- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/CognitiveServiceBase.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/anomaly/MultivariateAnomalyDetection.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/geospatial/AzureMapsTraits.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/language/AnalyzeTextLROTraits.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/text/TextAnalytics.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/translate/DocumentTranslator.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/translate/TextTranslator.scala
- cognitive/src/main/scala/com/microsoft/azure/synapse/ml/services/vision/ComputerVision.scala
- cognitive/src/test/scala/com/microsoft/azure/synapse/ml/services/language/AnalyzeTextLROSuite.scala
We have found that for Analytics LRO service, auth headers were not correctly passed as a result for polling the service was failing. We have now refactored the code and we are now passing in all headers. for polling
6. Make …
> chore: Fixing logic for polling in LRO tasks
